### ISSUE TITLE
Please consider adding Safari version

### ISSUE THREAD

**Issue by jauderho** [privacypass/challenge-bypass-extension#10]
Much thanks.

**Comment by balupton** [comment]
Why was this closed? Seems it should only be closed once there is a safari extension.

**Comment by alxdavids** [comment]
Sorry I should have added an explanation. Safari does not currently (and does not plan to AFAIK) support the WebExtensions framework. As such, this is not something that we are planning to implement any time soon.
If someone wants to contribute a PR that ports the extension to something that Safari will accept then we can re-open the issues. For now, and in favour of keeping a clean/maintainable issue list, this will remain closed.

**Comment by terryops** [comment]
> Sorry I should have added an explanation. Safari does not currently (and does not plan to AFAIK) support the WebExtensions framework. As such, this is not something that we are planning to implement any time soon.
> If someone wants to contribute a PR that ports the extension to something that Safari will accept then we can re-open the issues. For now, and in favour of keeping a clean/maintainable issue list, this will remain closed.

Safari 14 added support for WebExtensions framework, would you consider port the PrivacyPass to it?

**Comment by sycured** [comment]
Please reopen this issue to track the status

https://ngyikp.com/safari-14-webextensions/  includes an example to convert a Chrome extension to Safari: `xcrun safari-web-extension-converter /Users/user/Downloads/ghdnfbmfflgelndafnlgabneckbmfpla`
