### ISSUE TITLE
Doesn't work on Brave?

### ISSUE THREAD

**Issue by FireMasterK** [privacypass/challenge-bypass-extension#102]
The extension works perfectly on chrome but not on Brave?

The page doesn't refresh automatically after I solve the captcha.

**Comment by alxdavids** [comment]
Hi, Brave is not supported as a browser currently. I can keep this issue open as a feature request.

**Comment by durch** [comment]
I'll take a stab at this, at least exploratory, @alxdavids feel free to assign me to the issue

**Comment by alxdavids** [comment]
@durch Happy for you to have a go!

**Comment by AndreiJirohHaliliDev2006** [comment]
> Hi, Brave is not supported by Privacy Pass currently. I can keep this issue open as a feature request.

Do you have a page/article for roadmaps for this Chrome extension? If not yet, when you'll plan to have this?

**Comment by alxdavids** [comment]
I just tried out Privacy Pass in the latest version of Brave (`Version 1.7.92 Chromium: 80.0.3987.163 (Official Build) (64-bit)`) and it seemed to work fine for me. I will close this for now, but please comment if anyone still sees issues and I will reopen.

**Comment by FireMasterK** [comment]
Yep, works for me too now.
