### ISSUE TITLE
slow opening of "SingleFile" addon saved pages

### ISSUE THREAD

**Issue by rezad1393** [privacypass/challenge-bypass-extension#103]
Describe the bug
when I save a page with this addon and then open it if firefox , it freezes (or severely slows) firefox for some seconds. but this only happens with some addons enabled.
I disabled addons to see which one cause it and found 4 which enabling any one would cause this behavior.

I noticed that having these addon enabled only wont produce the result but only disabling them fixes the issue.
these are those addons.
" https://addons.mozilla.org/en-US/firefox/addon/requestcontrol/
https://addons.mozilla.org/en-US/firefox/addon/privacy-pass/
https://addons.mozilla.org/en-US/firefox/addon/ipvfoo-pmarks/
https://addons.mozilla.org/en-US/firefox/addon/smartproxy/"

I also noticed with the help of this addon (https://addons.mozilla.org/en-US/firefox/addon/website-information/) that singlefile pages seem to tell firefox that they have bogus domains (I am not sure but the addon shows that)
like this
(https://user-images.githubusercontent.com/7523164/58860429-5a1a6480-86c1-11e9-9648-1cc37e6212b1.png)
I have reported this issue to smartproxy addon page (salarcode/SmartProxy#89) and I am also reporting it here to see what causes this.

opening the pages saved by singlefile in chromium doesn't cause this issue but in chrome I have less addons installed but have the smartproxy one install too.

To Reproduce

    Go to '...'
    Click on '....'
    Scroll down to '....'
    See error

Expected behavior

Screenshots

Environment

    OS: archlinux
    Browser: firefox 6.70.1
    Version: latest

Additional context

this is a bug reported here for singlefile addon and smartproxy addon and it also shows up when your addon installed.
can you fix it like smartproxy did?

https://github.com/salarcode/SmartProxy/issues/89
https://github.com/gildas-lormeau/SingleFile/issues/225

**Comment by alxdavids** [comment]
I just read through the other issues you reported and it seems like a bug was logged with Firefox? If this is the case then I will close this issue?

**Comment by rezad1393** [comment]
when I enable this addon I get the issue.
so maybe until firefox fixes this (or maybe firefox thinks this is not an issue) , use the same fix ass the smartproxy author used?

this addon shouldn't access data: urls anyway so fixing this doesn't hurt the addon.
