### ISSUE TITLE
Not working on some sites

### ISSUE THREAD

**Issue by Eastkap** [privacypass/challenge-bypass-extension#105]
I have noticed that Privacy pass has stopped working in some sites such as [SNS](https://www.sneakersnstuff.com) or [BSTN](https://www.bstn.com) . Is this normal? Any plans to fix the lack of interaction of the extension?

**Comment by alxdavids** [comment]
Hi, it is possible that these websites have chosen to directly disable the acceptance of passes from the Privacy Pass extension. In these cases, we are unable to use Privacy Pass to bypass the CAPTCHA mechanism.

I think it may be useful to update the plugin UI in scenarios this occurs.

**Comment by Eastkap** [comment]
maybe it's better to keep this open until it's fixed in the UI

**Comment by BryanH** [comment]
If it matters, Privacy Pass seems to also not work on https://medium.com/

**Comment by alxdavids** [comment]
> If it matters, Privacy Pass seems to also not work on https://medium.com/

It seems to work fine on medium.com for me?

**Comment by ValZapod** [comment]
I cannot reproduce it. When I use tor console in Chrome, Cloudflare just blocks me with Error 1020.

**Comment by BryanH** [comment]
@alxdavids @ValZapod Well, now I can't seem to reproduce, so ¯\_(ツ)_/¯
