### ISSUE TITLE
What about the network administrators?

### ISSUE THREAD

**Issue by nadams810** [privacypass/challenge-bypass-extension#13]
I had originally typed up an extremely long rant - but it can be summarized simply as - what about the network administrators behind systems that may be infected?

I recently started getting the dreaded cloudflare captcha page and their, unresponsive and dismissive, twitter support directed me to this extension. As a network administrator PLEASE get cloudflare techs in a meeting and go "we need a way for network administrators to figure out why their end users were directed to this plugin". As a network administrator, I would rather smack the user for having a compromised system than you encouraging them to not to tell me their computer may be infected by installing this plugin/extension. 

However, if all end-users see is a worthless "you may or may not be infected - but install this chrome extension because that is what the cool kids are doing" - that doesn't help me, as the network administrator, clean the system and get back onto the internet's good graces. Yes, I do understand, if cloudflare provided an email or contact form the end user would contact them. But, I'm sure cloudflare could come up with a way to verify that it is indeed the network administrator contacting them and not just a random end user of the network.

For the record - I pay for a static range of IPs from my ISP. My IPs do have correct whois on them for people to contact me in the event that bad things(tm) are coming from my network. I did check over 230 blacklists and I'm not listed on any of them (nor do I recall ever being on one). And cloudlfare seems to be unable to tell me why I'm seeing the page which has me quite concerned if they don't actually have insight into their own network and infrastructure....

**Comment by alxdavids** [comment]
This isn't really what Privacy Pass is being used to solve. Privacy Pass seeks to reduce the burden on users who are wrongly categorised as harmful when accessing the Cloudflare network. While yes, if a user ius associated with a compromised system, then they are more likely to see CAPTCHAs, Privacy Pass does not magically solve the problem. They still have to solve at least one CAPTCHA for every N (typically 30) tokens. A network administrator can still attempt to troubleshoot the issue, Privacy Pass just makes browsing a little easier in the mean time.

I'm going to close this as an issue, but if you still feel strongly about this then feel free to reopen it.
