### ISSUE TITLE
Not working in Chrome

### ISSUE THREAD

**Issue by QAInsights** [privacypass/challenge-bypass-extension#137]
I installed Privacy Pass extension in the latest version of Chrome, I visited this site to check the extension. But its still I need to solve the captcha challenge manually. Also I tried with various pages, it seems that the extension is not working as intended. Can you please check?

Chrome: 78
OS: Windows 10

**Comment by alxdavids** [comment]
For Privacy Pass to work, you first need to solve one CAPTCHA (e.g. at https://captcha.website). This provides you with 30 tokens that can be used to pass other websites that display CAPTCHAs (this doesn't include captcha.website, this website is only set up to allow you to receive passes). Can I just check which version of the extension you are running, and whether you have completed above?

**Comment by QAInsights** [comment]
Yes, I did solved the CAPTCHA and received the 30 tokens. I installed 2.0.2.

**Comment by alxdavids** [comment]
Do you have an example website that displays a CAPTCHA that doesn't work for you?

**Comment by QAInsights** [comment]
I reinstalled plugin 2.0.2. I am not able to get tokens, after solving the challenge, SUBMIT button is going invisible.

**Comment by alxdavids** [comment]
I'm not sure this is related to Privacy Pass, this seems related to interacting with a CAPTCHA in your browser.

**Comment by QAInsights** [comment]
I am able to get the passes, but it is not working in FF and Chrome. URL I tried is https://recaptcha-demo.appspot.com/recaptcha-v2-checkbox.php

**Comment by alxdavids** [comment]
This isn't what the Privacy Pass Cloudflare integration is intended for, it's only intended to allow you to bypass CAPTCHA challenges provided by the Cloudflare network.
