### ISSUE TITLE
View on Github link is broken in Chrome extension

### ISSUE THREAD

**Issue by QAInsights** [privacypass/challenge-bypass-extension#138]
In the Chrome extension, View on Github link is broken. It is redirecting the users to https://github.com/cloudflare/challenge-bypass-extension

Please check.

**Comment by alxdavids** [comment]
Which version of Privacy Pass are you running? It seems fine to me on v2.0.2 but also this hasn't been changed in recent versions. In the source code: https://github.com/privacypass/challenge-bypass-extension/blob/master/addon/popup/bc-plugin.html#L39?

**Comment by QAInsights** [comment]
I installed it from here via Cloudflare blog https://chrome.google.com/webstore/detail/cloudflare-privacy-pass/ljcnjeipfdmoflddjjdlmljaagkhnbff

**Comment by alxdavids** [comment]
Ah! That's an old version of the extension, try this link instead: https://chrome.google.com/webstore/detail/privacy-pass/ajhmfdgkijocedmfjonnpjfojldioehi?hl=en

**Comment by QAInsights** [comment]
After installing the latest version, link is working fine.
