### ISSUE TITLE
Clicking on Log Redemption to Console reduces the tokens

### ISSUE THREAD

**Issue by QAInsights** [privacypass/challenge-bypass-extension#139]
By clicking on Log Redemption to Console in the extension, decreases the number of tokens by 1. Is this expected behavior? Please clarify.

**Comment by alxdavids** [comment]
This is expected behaviour, if you look in the console there is redemption data that can be used to redeem with the public redemption API at https://privacypass.cloudflare.com/api/redeem. See the [documentation](https://privacypass.github.io/api-redeem).
