### ISSUE TITLE
Privacy Pass doesn't work on Firefox for Android

### ISSUE THREAD

**Issue by bungabunga** [privacypass/challenge-bypass-extension#14]
If I install Privacy Pass on Firefox for Android I never get pass Clouflare's captcha. One captcha after anothe after another...

Sony Xperia XZ
Android 7.1.

**Comment by futtetennista** [comment]
I'm experiencing the same problem with Firefox Version 57.0 on OxygenOS 5.4.1 Android version 7.1.1 patch level 1 August 2017.

**Comment by alxdavids** [comment]
This extension isn't intended to work on mobile devices currently.

**Comment by acannon828** [comment]
@alxdavids is there a plan/timeline for supporting mobile?
