### ISSUE TITLE
Buggy - not working 90% of the time

### ISSUE THREAD

**Issue by benzon** [privacypass/challenge-bypass-extension#146]
Okay so i used the plugin for authing to forum.fivem.net, let me say it this way 90% of the time it dos not work at all, and all other sites i have visited with this privacy pass on ye it dossent rly work.

It's hard to tell whats wrong but right now it's just a useless plugin that dos nothing in my eyes.

**Comment by alxdavids** [comment]
Hi, I just had a look at this, and it does seem that there is an issue in that tokens are spent but a CAPTCHA is still displayed initially. If you then refresh the page, it works fine.

I have a feeling that this is down to the redirect from forum.fivem.net -> https://forum.cfx.re/.  If you navigate to https://forum.cfx.re/ directly it works fine.

**Comment by marcus188** [comment]
Hello, how can get own tokens? I have a script and i use it in linux for bypass captcha, and i need tokens, my script use some tokens from ''tokens.json''

format tokens is  :`"token": [141, 100, 234, 111, 57, 7, 62, 118, 149, 37, 146, 196, 220, 191, 37, 35, 97, 47, 20, 73, 13, 0, 18, 9, 179, 42, 113, 194, 135, 135, 81, 34],
    "point": "SXWZli2LWyq287oJhNM0fGR3ozpi9CCnXJVRvnMgEHbq3DD2aFFP7N7DeQ2r6m+sWLwcrinCGKOGoXt3bzGkVg==",
    "blind": "0x87c5b139b9165d2822547f7c9823889aeff503de9d8290b7034cd21f197471e1"
}, {`

How is posible to get tokens?

**Comment by BryanH** [comment]
@marcus188 You should never ask a new question in a discussion about something else if you want an answer.

If you have questions on how to use this (or any) software, you might check [SuperUser](https://superuser.com/) or [search the web](https://duckduckgo.com/?q=challenge-bypass-extension).

**Comment by armfazh** [comment]
@benzon does the solving rate improved with the newest version? 
please (re-)open a new ticket if you still see issues.
