### ISSUE TITLE
AMO site reports Privacy Pass is corrupt 

### ISSUE THREAD

**Issue by Telmesomething** [privacypass/challenge-bypass-extension#15]
Tried to install PP on Basilisk this morning, but get a message that the file is corrupt and cannot be installed.

![privacy_pass_corrupt](https://user-images.githubusercontent.com/33827636/33238605-711edd86-d291-11e7-96c0-8693d8b8d961.PNG)

**Comment by PacoBell** [comment]
Also getting this error in Orfox 1.4.1-RC-1/TorBrowser 7.0-1.

**Comment by PacoBell** [comment]
Lines 93 and 117 in manifest.mf look to be corrupt. Please fix and re-upload.

**Comment by alxdavids** [comment]
Basilisk and Orfox are not officially supported browsers for now, so I am going to close this issue. PRs are welcome if anyone would like to make changes to the manifest.
