### ISSUE TITLE
Needs rewrite for hCaptcha

### ISSUE THREAD

**Issue by erkinalp** [privacypass/challenge-bypass-extension#157]
https://blog.cloudflare.com/moving-from-recaptcha-to-hcaptcha/

**Comment by alxdavids** [comment]
Under most conditions I think the extension should work, but I'm aware of some issues that we're going to solve in a future release. I'll try to find the time to get that out soon.

**Comment by Jookia** [comment]
I can confirm this works with hCaptcha for the most part

**Comment by wwbfred** [comment]
I could only get five tokens in one verification and lost tokens frequently.
I think further update is necessary.

**Comment by myfreeweb** [comment]
Yeah, the 'get more passes' link now goes to the hCaptcha page, but it doesn't force the page to only give tokens, so the page spends them if they're available.

Also why does it only give five tokens? That's way too little >_<

**Comment by alxdavids** [comment]
Thanks for the extra information, still working on getting some more changes out before the next release that will make future updates a little easier. Once these changes are done, I'll look to release a new version to the extension stores.

As a temporary workaround, the current branch of master should have the necessary fixes for hCaptcha and so you may be able to install the extension directly from source if you would like to try that out.

**Comment by alxdavids** [comment]
> Also why does it only give five tokens? That's way too little >_<

This is a value specified by the hCaptcha configuration that is used.

**Comment by devomaa** [comment]
Can confirm on Firefox Nigthly

**Comment by hsafe** [comment]
hcaptcha in my case is breaking everything... incluing getting passes process too

**Comment by devomaa** [comment]
For me, it even doesn't give me passes.
OS: Windows 10 Build 1909
Privacy Pass Version: 2.0.5
Firefox Nightly Version: 77.0a1 (2020-04-22) (64-bit)

**Comment by durch** [comment]
@alxdavids let me know if we can help out here :)

**Comment by alxdavids** [comment]
@durch I think we should be all good, going to release a new version (hopefully today) to FF and Chrome stores that should fix this. Will let you know if we need anything!

**Comment by alxdavids** [comment]
New versions have been uploaded to Chrome and FF stores that should fix these issues.

**Comment by alxdavids** [comment]
Can anyone here confirm whether updating the extension to v2.0.6 fixes these issues for them?

**Comment by devomaa** [comment]
Yes, it does.

**Comment by alxdavids** [comment]
Great! I am going to close this issue now. If any problems resurface, then I will reopen it.
