### ISSUE TITLE
Request: use white text (or lighter blue background) on pass count notification

### ISSUE THREAD

**Issue by ahydronous** [privacypass/challenge-bypass-extension#159]
The current black text is hard to read because it has poor contrast with the blue that is being used

**Comment by armfazh** [comment]
Hi @ahydronous , what specific text are you referring, please attach an image if possible.

**Comment by ahydronous** [comment]
Apologies for the ambiguity, I meant the badge on the Privacy Pass extension icon in the menu bar, but it has since been changed to white text!

See attached image.

![image](https://user-images.githubusercontent.com/57762816/209832937-027e155c-8848-4440-9751-5ec5d0003919.png)

**Comment by armfazh** [comment]
so blue&white makes a good contrast? otherwise use this generator to suggest us a combination. 

https://www.learnui.design/tools/accessible-color-generator.html
