### ISSUE TITLE
Cannot get captcha on a IPv6 only connection

### ISSUE THREAD

**Issue by miyurusankalpa** [privacypass/challenge-bypass-extension#170]
This extension worked great on IPv6 only connections before and now it simply does not work. 
hcaptcha website is IPv4 only so clicking the link go to dead site. 

making matters worse http://captcha.website/ still works but hcaptcha does not load.

![image](https://user-images.githubusercontent.com/1833185/81373388-4de12780-911a-11ea-9a0d-1c54444627d6.png)

Please fix this, because of the this extension is useless.

**Comment by alxdavids** [comment]
This has nothing to do with Privacy Pass, it's a problem that you're experiencing with the CAPTCHA provider as you have pointed out. Perhaps you should take it up with them instead.
