### ISSUE TITLE
Passes don't allow access through Cloudflare

### ISSUE THREAD

**Issue by ejaaubbvwimasaximk-awdrt-com** [privacypass/challenge-bypass-extension#174]
Collecting Cloudflare passes by solving the hCaptcha works fine, but the passes do more harm than good.

Instead of allowing me to pass through Cloudflare without solving the hCaptcha, my browser just keeps reloading the page until I run out of passes.
Roughly once every fifty refreshes my browser prompts a dialog asking me to confirm before resending form data or something like that... after which I can pass Cloudflare's hCaptcha once.

This issue happens both with Firefox and with Chrome.

**Comment by alxdavids** [comment]
We're now only accepting issues that adhere to one of the templates that we have provided. Issues in free-form are impossible to diagnose without learning more about the user's expectations & platform etc. I'm going to close this issue, you can reopen a new issue following one of the issue templates that we have provided.

FWIW this isn't behaviour that I have noticed so we will need more information.
