### ISSUE TITLE
You cannot have more than 5 hCaptcha tokens at once

### ISSUE THREAD

**Issue by Catsaregoo** [privacypass/challenge-bypass-extension#178]
Hi **Privacy Pass** team, I need some help with my issue.
For now, you cannot have more than **5** hCaptcha tokens at once!
Please make a feature that **lets you choose between adding and using tokens**. Thanks!

Sincerely,
**catsaregoo**

**Comment by alxdavids** [comment]
This is intentional behaviour as it defined by the hCaptcha configuration. If you would like to request a new feature, please put it in the issue format that has been provided, so that we have a better idea what the change would look like.
