### ISSUE TITLE
REPOST: Multiple hCaptcha Points

### ISSUE THREAD

**Issue by rocord01** [privacypass/challenge-bypass-extension#179]
---
name: **Multiple hCaptcha Points**
about: **a feature has a option that lets you choose to earn passes or use passes**
title: **Multiple hCaptcha Points**
labels: **passes, hCaptcha** 
assignees: ?

---

**Is your feature request related to a problem?** 
_No, it is not._
If so, make sure your problem hasn't been listed before.

**Describe the solution you'd like**
_a feature that lets you choose to earn passes or use passes
i would put a switch in place of "**Log CF Redemption To Console**"_
Please describe a description of what can be improved, or what you want to happen.

**Additional context**
_Not any additional context_
Add any other context about the feature request here.

**Comment by alxdavids** [comment]
Thanks for rewriting this, we'll take some time to think about whether this would be possible.

**Comment by erkinalp** [comment]
If possible, even automatic detection.

**Comment by ValZapod** [comment]
> If possible, even automatic detection.

That is done here. https://github.com/privacypass/challenge-bypass-extension/commit/a82e05be8979950e4580ae43b500bb15fb81579e

**Comment by ValZapod** [comment]
Fix version, https://github.com/privacypass/challenge-bypass-extension/files/5736374/2.7.0.zip unpack install in dev mode in chrome://extensions

**Comment by rocord01** [comment]
did anyone forget about this

**Comment by thibmeu** [comment]
hCaptcha [announced](https://www.hcaptcha.com/privacy-pass) the end of their support for the legacy Privacy Pass protocol in favor of the IETF version.

I'm closing this ticket.
