### ISSUE TITLE
"Problem: Tagging" glitch

### ISSUE THREAD

**Issue by kousu** [privacypass/challenge-bypass-extension#18]
https://privacypass.github.io/protocol/ says

> A third party with access to P, sP, Q, sQ can use DLEQ(P:sP == Q:sQ) to verify that the same value s was used without knowing what s is.

Couldn't the third party just compute sP/P?

**Comment by kousu** [comment]
Relatedly, Scenario 5 says

> The server picks a generator point G and publishes sG somewhere where every client knows it.
Issue
>
> ```
> T = Hash(t) 
> bT ->
>	  <- sbT, DLEQ(bT:sbT == G:sG)
> ```
>
> The client can then check to see that the server used the same s, since everyone knows sG.

If the "third party" is the client, and the third party needs "access to P, sP, Q, sQ", then is G published by the server too?

**Comment by alxdavids** [comment]
> Couldn't the third party just compute sP/P?

No, this would require the discrete log problem to be easy in the given elliptic curve that is used (NIST P-256). This is widely believed to be computationally difficult.

> If the "third party" is the client, and the third party needs "access to P, sP, Q, sQ", then is G published by the server too?

Yes G is published, it is analogous to a generator of the cyclic group that is mirrored by the curve that we use.
