### ISSUE TITLE
Doesn't really work.

### ISSUE THREAD

**Issue by DarkAlchy** [privacypass/challenge-bypass-extension#180]
I am not sure where the issue is but I try to go to a site and there is the captcha but it directed me to install this and I did but even though I see the passes in the upper right corner I still have to do the captcha.  I use incognito mode and the addon is on in incognito mode but doesn't really work.  This makes me wonder what is Cloudfare really doing here since the addon sees I have hCaptcha and Cloudfare passes but Cloudfare is demanding I be put off since I choose to use a privacy mode since my data is my own and all they need worry about is that the passes on the addon are valid.

**Comment by alxdavids** [comment]
I really have no way of understanding whether there is an issue here or whether the use-case is being misunderstood. If you think there is a bug, then I would advise opening a new issue in one of the provided formats so that we can look into it.
