### ISSUE TITLE
cloudflare counter is not working

### ISSUE THREAD

**Issue by yujiangqaq** [privacypass/challenge-bypass-extension#185]
**Describe the bug**
cloudflare counter is not working
After clicking cloudflare get more passes, the jumped site can only see the verification module of hcaptcha. After captcha, the counter of hcaptcha will be increased but the counter of cloudflare will not be increased.

**To Reproduce**
1. Go to Plugin
2. Click on cloudflare get more passes
3. See error

**Expected behavior**
After clicking cloudflare get more passes and completing captcha, the cloudflare counter will be increased

**System (please complete the following information):**
 - OS: [windows]
 - Browser [chrome, firefox]
 - Browser Version [chrome79,firefox77.0.1 ]
 - Privacy Pass Version [2.0.6 ]
 - Did you install Privacy Pass from this repository or from the browser store?
 browser store

**Comment by alxdavids** [comment]
Does this happen on all websites? Or just a particular one? It may be that the Cloudflare customer has disabled Privacy Pass support.

**Comment by robsonsobral** [comment]
It took me sometime to discover this is the addon braking CloudFlare login.

**Comment by yujiangqaq** [comment]
This happened on the page https://captcha.website/, which is the page redirected to after opening cloudflare-get more passes. Clicking I am a human will get the hcaptcha token, not the cf token. . .
And you cannot skip captcha and ddos protection when visiting websites protected by cf
In other words, this plugin does not work on cloudflare protected websites

**Comment by migueldemoura** [comment]
I'm unable to reproduce the issue with the Firefox `100.0.2 (64-bit)` and Chrome `Version 101.0.4951.64 (Official Build) (x86_64)`, feel free to reopen if the issue persists!
