### ISSUE TITLE
Request activeTab permission instead of "<all_urls>"

### ISSUE THREAD

**Issue by krsch** [privacypass/challenge-bypass-extension#186]
I don't like granting extensions "<all_urls>" permission as it increases attack surface on my browser. Google Chrome has "activeTab" permission that would only grant an extension access to the page after I press a button. I see no problem in pressing a button to pass captcha. It would be great if I could use Privacy Pass this way.

**Comment by alxdavids** [comment]
I personally don't think this is a very good idea and this issue doesn't give enough details about what changes would need to be made. If you would like to create an issue in one of the formats that are provided with detailed instructions about the interaction that you would look like to see then go ahead.

However, realistically, I don't think this is a change that we will be making. My advice would be to fork the repo and try and make the change yourself.
