### ISSUE TITLE
ReCaptha Support

### ISSUE THREAD

**Issue by AmyRose1288** [privacypass/challenge-bypass-extension#189]
some websites is using ReCaptha instead of hCaptha,hopefully this could support these

**Comment by njcyx6649250** [comment]
2nd this request. Google ReCaptha is still very popular among all the websites.

**Comment by alxdavids** [comment]
Yep. Unfortunately this would require reCaptcha to explicitly support the Privacy Pass extension and so there is little that we can do until that happens.

**Comment by ValZapod** [comment]
> reCaptcha to explicitly support the Privacy Pass extension and so there is little that we can do until that happens.

Did you even ask google??
