### ISSUE TITLE
"Problem: Malleability" glitch

### ISSUE THREAD

**Issue by kousu** [privacypass/challenge-bypass-extension#19]
https://privacypass.github.io/protocol/ says

> It’s possible to create an arbitrary number of pairs of points that will be verified. The client can create these points by multiplying both T and sT by an arbitrary number a. If the client attempts to redeem aT and a(sT), the server will accept it. This effectively gives the client unlimited redemptions.

but nowhere does the rest of the doc imply that the server is tracking `T`s that it has seen. Is that an assumption? It should be written in, I think. That seems like an expensive proposition. And does that assumption apply to all scenarios or just scenario 4? Does the cloudflare server track all tokens it has seen or is there some kind of clever stateless signature scheme going on?

**Comment by alxdavids** [comment]
The server does indeed keep track of the tokens T_i that it witnesses. If it did not then double-spending of tokens would be possible, so it is not an assumption but a requirement. I agree that the website could make this clearer, though we explain this in our other documentation. 

It is not too expensive to do this, there are many efficient data storage techniques, we currently use Bloom filters. Besides this storage can be reset when key rotation occurs.
