### ISSUE TITLE
Brave comptatibility

### ISSUE THREAD

**Issue by ghost** [privacypass/challenge-bypass-extension#190]
**Describe the solution you'd like**
Brave should be compatible with this extension, it almost never works on brave.

**Additional context**
Evidence of it not working 
https://imgur.com/dN87Ghz
Note: It doesn't work on all sites

**Comment by KingCurry12** [comment]
Bump

**Comment by alxdavids** [comment]
Thanks, for filing this. I don't really have the time to take this on at the minute, but I'll update this when I get around to it.

**Comment by Nicster205** [comment]
Same here, I've been using brave for a while and since its blowing up now you should really add better compatibility.

**Comment by migueldemoura** [comment]
I'm unable to reproduce the issue with Brave `[Version 1.38.119 Chromium: 101.0.4951.67 (Official Build) (x86_64)]`, feel free to reopen if the issue persists!
