### ISSUE TITLE
Backup my tokens?

### ISSUE THREAD

**Issue by axzxc1236** [privacypass/challenge-bypass-extension#192]
**Describe the solution you'd like**
I'm currently using privacy pass in my Firefox, it works great, I wonder if I can make a backup to my tokens in case (1) I need to use another computer (2) I need to reinstall my computer (3) solving on a PC and redeem on mobile ...etc  
(I am also wondering if there is a way to pile up tokens, like, solving captchas for one day and don't worry about captcha for two months?)

**Additional context**
I just found this a few minutes ago and I am already loving this idea, thank you whoever worked on this.

**Comment by Lekensteyn** [comment]
You should be able to backup your tokens by copying your Firefox profile folder.

Firefox Sync could in theory work, but apparently "localStorage" data is not included, so in practice tokens cannot be transferred between devices using that method.

Tokens may not have an infinite lifetime and as you get a sufficient amount of tokens every time, there should not be a need to stack up captcha solutions.

**Comment by ValZapod** [comment]
> Tokens may not have an infinite lifetime

Sorry for the dumb question, but what is the lifetime? And they are not deleted from extension automatically, are not they??

**Comment by Shahen20** [comment]
Backup my token 192

**Comment by thibmeu** [comment]
Close for inactivity
