### ISSUE TITLE
Privacy Pass browser extension is not available in the Chrome Web Store

### ISSUE THREAD

**Issue by CoolSpot** [privacypass/challenge-bypass-extension#197]
**Describe the bug**
Link to Chrome extension (https://chrome.google.com/webstore/detail/privacy-pass/ajhmfdgkijocedmfjonnpjfojldioehi) leads to page 404.
[Search results](https://chrome.google.com/webstore/search/Privacy%20pass?_category=extensions) in the Chrome Web Store don't contain the Privacy Pass extension.

**To Reproduce**
1. Go to the official site for Privacy Pass - [https://privacypass.github.io/](https://privacypass.github.io/)
2. Click on "Install" -> "Chrome logo" icon
3. Observe Google's page 404: "The requested URL was not found on this server. That’s all we know."

Another way to reproduce the behavior:
1. Go to the official Chrome Web Store - [https://chrome.google.com/webstore/category/extensions](https://chrome.google.com/webstore/category/extensions)
2. Type in "Privacy Pass" into "Search Extensions" field on the top left of the screen, press enter to get results
3. Observe search results containing three variations of the "Flappy Bird" game, but no "Privacy Pass" extension.

**Expected behavior**
Expected the Privacy Pass browser extension to be available in the Google Chrome Web Store.

**System (please complete the following information):**
 - OS: Linux Mint 19.3 (based on Ubuntu 18.04)
 - Browser: Chromium
 - Browser Version: Chromium Version 85.0.4183.83 (Official Build) Built on Ubuntu , running on LinuxMint 19.3 (64-bit)
 - Privacy Pass Version: any
 - Did you install Privacy Pass from this repository or from the browser store? N/A

**Additional context**
Tested on PC via Spectrum home internet (Los Angeles) and on iPhone via T-Mobile LTE (Los Angeles) with the same result.
Same result in incognito and in regular browsing mode.

**Screenshots**
![image](https://user-images.githubusercontent.com/3990370/95385611-15996d00-08a3-11eb-9d87-80e8caf8bea5.png)
![image](https://user-images.githubusercontent.com/3990370/95385684-2cd85a80-08a3-11eb-8e99-fe18ba35502f.png)

**Comment by alxdavids** [comment]
Thanks for reporting, I think this might be a permissions issue. I've created a PR. Once it's merged we'll update the store version.

**Comment by alxdavids** [comment]
Reopening until the new version is back in the store.

**Comment by Nicster205** [comment]
Can vouch for this, I'm so annoyed and can't get passed Cloudflare, try getting up this as soon as possible, please.

**Comment by rajib884** [comment]
Is this one legit? https://chrome.google.com/webstore/detail/privacy-pass/odniikpejlhbjandolpbjlpmhkhjmaba 
Can be found by searching privacy pass on Chrome web store

**Comment by alxdavids** [comment]
> Can vouch for this, I'm so annoyed and can't get passed Cloudflare, try getting up this as soon as possible, please.

Working on it, the review process is a little involved but hopefully we'll have it back up in the next day or so. In the meantime, note that the extension can also be used by cloning the repository and installing the extension directly into Chrome, via chrome://extensions.

**Comment by Nicster205** [comment]
alxdavids, I tried but I need the repository, there are no releases and the master branch doesn't work for it, where can I get the repository?

**Comment by yidasanqian** [comment]
> > Can vouch for this, I'm so annoyed and can't get passed Cloudflare, try getting up this as soon as possible, please.
> 
> Working on it, the review process is a little involved but hopefully we'll have it back up in the next day or so. In the meantime, note that the extension can also be used by cloning the repository and installing the extension directly into Chrome, via chrome://extensions.

Could you release the  latest crx package.

**Comment by rizqiimani** [comment]
I cannot install it by cloning the master repository, I did use `git clone`, and drag and dropping the downloaded folder into Extensions page, I also turned on Developer Mode on. Here's an error that I get:
![image](https://user-images.githubusercontent.com/55040411/96358709-7abb5100-1134-11eb-9eca-f3bc811b58bf.png)

**Comment by Neobond** [comment]
So it's still not available in the Chrome web store.

**Comment by alxdavids** [comment]
> So it's still not available in the Chrome web store.

Yeah, unfortunately the review process is still not complete. I'm not exactly sure what the hold up is. Hopefully it will be through soon.

> I followed instructions on Quickstart and had to tinker and modify some steps, here's what I go through, please bear with me:

Thanks for taking the time to go through this. :+1: Indeed the documentation could probably do with some work. If you'd like to create a PR to add a more user-friendly set of instructions based on your experience then this would really help us.

**Comment by Klapkaak078** [comment]
> > So it's still not available in the Chrome web store.
> 
> Yeah, unfortunately the review process is still not complete. I'm not exactly sure what the hold up is. Hopefully it will be through soon.
> 
> > I followed instructions on Quickstart and had to tinker and modify some steps, here's what I go through, please bear with me:
> 
> Thanks for taking the time to go through this. 👍 Indeed the documentation could probably do with some work. If you'd like to create a PR to add a more user-friendly set of instructions based on your experience then this would really help us.

Are you able to release a build crx that we can load in chrome? Because I can’t get it Working because all folders and files are differently than the files in the crx file. Thank you!

**Comment by Jas0n99** [comment]
Glad I'm not the only one that noticed that privacy pass was missing from the chrome store... Pretty annoying as one site I visit seems to give me a stupid hcaptcha DAILY... Would be nice to be able to avoid it...

**Comment by gcpmusic** [comment]
Still not available on the store. Can you please make the download here?
Thanks.

**Comment by mindfocus** [comment]
Still not available on the store.

**Comment by Nicster205** [comment]
Bump, its still not available on the store and i hate downloading it and using make install

**Comment by Jas0n99** [comment]
It's on the chrome store now! Quick, add it to your browsers before it disappears again!

**Comment by gcpmusic** [comment]
Thank you. However, 3.0.7 update is available only for Chrome. Firefox still on 2.0.6?

**Comment by armfazh** [comment]
PrivacyPass back to the Chrome Web store.
Link: https://chrome.google.com/webstore/detail/privacy-pass/ajhmfdgkijocedmfjonnpjfojldioehi
