### ISSUE TITLE
"Scenario 4" oversight

### ISSUE THREAD

**Issue by kousu** [privacypass/challenge-bypass-extension#20]
https://privacypass.github.io/protocol/ says

> sign a message that relates to the redemption [...]
> HMAC(sT, M) for a message M

but it never defines `M`. It also says redemption is just

> ```
> t, HMAC(sT, M) ->
> ```

which suggests that M must be computable server side somehow. But what is it? Is it a nonce? A timestamp? Could just set M = T = hash(t) ?

**Comment by alxdavids** [comment]
Yep, you're right, M should be sent as a separate component.

**Comment by alxdavids** [comment]
This has been fixed.
