### ISSUE TITLE
Clear cookies for https://captcha.website/ does not work anymore

### ISSUE THREAD

**Issue by ValZapod** [privacypass/challenge-bypass-extension#203]
That is this code.

https://github.com/privacypass/challenge-bypass-extension/blob/75285406d89bcb244b9565c3714f918a99d18fe0/src/ext/listeners.js#L68

Just clearing cookies does work and allows to open cloudflare window instead of contents of https://captcha.website/ that is not needed.

**Comment by alxdavids** [comment]
You should resubmit this issue in one of the accepted formats so that we can properly investigate the problem.

**Comment by ValZapod** [comment]
But it does not work! Try to visit https://captcha.website/ second time, it will not show cloudflare page and cookies will not be cleaned.
