### ISSUE TITLE
Tokens unexpectedly deleted 

### ISSUE THREAD

**Issue by nadesco** [privacypass/challenge-bypass-extension#205]
This is more a question than a bug so apologies if it's in the wrong section, but I was wondering whether it's possible to keep Cloudflare and hCaptcha tokens even after clearing cookies? I read [a comment here](https://github.com/privacypass/challenge-bypass-extension/issues/177) that says tokens are stored in the browser's local storage. That said, I use an addon called [Clear Browsing Data](https://github.com/dessant/clear-browsing-data), which has options to clear the following:

Cookies
Browsing history
Cached images and files
Autofill form data
Download history
Service Workers
Plugin data
Saved passwords
Local storage data
IndexedDB data 

At the moment I have only Cookies enabled. The Local storage data box is not checked, but when I clear cookies using the CBD app all Privacy Pass tokens are deleted. When I uncheck Cookies the tokens remain and Privacy Pass works as it should. Is there any way I can prevent the tokens from being deleted without breaking the functionality of CBD? 

Firefox 82.0, Mac 10.14.6
Privacy Pass 2.0.6

Thanks

* forgot to mention that the Clear Browsing Data app doesn't have any whitelist

**Comment by alxdavids** [comment]
We use the localstorage APIs for storing data in the extension and your addon deletes data from this storage, so that is the reason.
