### ISSUE TITLE
"Scenario 6" typo

### ISSUE THREAD

**Issue by kousu** [privacypass/challenge-bypass-extension#21]
https://privacypass.github.io/protocol/ says

> Issue
>
> ```
> T1 = Hash(t1) 
> T2 = Hash(t2)
> T3 = Hash(t3)
> b1T1 ->
> b2T2 ->
> b3T3 ->
>		<- sbT1, DLEQ(b1T1:sbT1 == G: sG)
>		<- sbT2, DLEQ(b2T2:sbT2 == G: sG)
>		<- sbT3, DLEQ(b3T3:sbT3 == G: sG)
> ```

shouldn't those read DLEQ(bnTn:sb**n**T1 == G: sG)? Each token has a different blinding factor right?

**Comment by alxdavids** [comment]
Fixed.
