### ISSUE TITLE
Privacy Pass not Collecting Cloudflare Captchas

### ISSUE THREAD

**Issue by ripnonfegames** [privacypass/challenge-bypass-extension#212]
**Describing the bug**
Currently, I am trying to go onto [v3rmillion.net](https://v3rmillion.net/)
When I try to do the captcha, Privacy pass does not catch the token, 
It doesn't work on [captcha.website](https://captcha.website/) either, I finish the captcha, and Privacy Pass doesn't Collect Tokens.

**To Reproduce**
1. Go to [captcha.website](https://captcha.website) or [v3rmillion.net](https://v3rmillion.net/)
2. Click on the captcha on Cloudflare
3. Do the captcha.
4. See privacy pass hasn't gotten any tokens.

**Expected behavior**
I do the captcha and I get 30 Cloudflare tokens in Privacy Pass.

**System**
 - OS: [Windows]
 - Cloudflare tokens
 - Browser [Chrome]
 - Browser Version [87.0.4280.66 (Official Build) (64-bit)]
 - Privacy Pass Version [latest]
 - Privacy pass is installed from the Chrome Store.

**Comment by Dhanurjan** [comment]
try this link - https://crackwatch.com/login
Cloudflare not working to me but hCaptcha working fine for me.
Using privacy pass version 2.0.7. (installed from chrome webstore)

**Comment by ValZapod** [comment]
Fix version, https://github.com/privacypass/challenge-bypass-extension/files/5736374/2.7.0.zip unpack install in dev mode in chrome://estensions

**Comment by ValZapod** [comment]
This site uses google captcha, it is not suitable for this plugin. Not anymore, Clouflare get rid of google captcha.

**Comment by migueldemoura** [comment]
We've released quite a few improvements since then, so closing this. Please feel free to open a new issue if it persists!
