### ISSUE TITLE
How do I hack Privacy Pass?

### ISSUE THREAD

**Issue by idgas01** [privacypass/challenge-bypass-extension#213]
I was surprised that my website that I visited requested captcha because I have Privacy Pass and I should have been stocked up on passes.  So I moved the Privacy Pass icon back on my navigation bar, and I saw that I had 5 hCaptcha passes and wanted to add more.  I clicked "get more" and it opened up a wall of text.  I scrolled down and saw a captcha so I completed it.  Didn't add any more passes.  But it changed my total of 5 hCaptcha passes to 4.  So I scrolled down the wall of text and saw something about an icon showing up in URL bar once I do the captcha.  So I filled out the captcha on the wall of text page again.  My new total was now 3 hCaptcha passes and no icon changes and no icon showed up in the URL bar.  And when I visited the aforementioned site, nothing changed.  No captcha requests.  So here I am spending all this time and instead of getting more passes, I was actually losing them.

I just want to be done with this.  Is there a config file I can edit to add 100 hCaptcha passes?  I'd rather do it that way so I don't have to play these annoying games that don't work.

**Comment by Klapkaak078** [comment]
Lol, all code from hCaptcha is server side, you have to hack their server.

**Comment by ValZapod** [comment]
https://github.com/privacypass/challenge-bypass-extension/files/5736374/2.7.0.zip Here you are, unpack, install in dev mode in chrome://extensions/
