### ISSUE TITLE
Is there a Privacy Pass alternative?

### ISSUE THREAD

**Issue by idgas01** [privacypass/challenge-bypass-extension#214]
I have 130 Cloudflare passes.  That's great.  I won't have to worry about those for a while.  But I only have 2 hCaptcha passes.  When I click "get more" it doesn't give me more.  It redirects me to a website and I'm told I am supposed to blacklist that website, but no instructions how.  But even if I figure out how to blacklist the website that the "get more passes" buttons brings up, then what?  I think that I can only get a maximum of 5 hCaptcha passes?  So that means I will have to constantly add more (if I ever figure out how).  Get 5 hCpatcha passes.  A day or two later, get 5 more.  And again, again, and again.  Forever.  It's such a bother.  Is there an extension or user script out there that does the same thing but better?

**Comment by Klapkaak078** [comment]
There is a alternative, its their own hCaptcha accessibility access. But it gets really fast rate limited. https://www.hcaptcha.com/accessibility

**Comment by ValZapod** [comment]
Here you are. https://github.com/privacypass/challenge-bypass-extension/files/5736374/2.7.0.zip Unpack zip, install in dev mode.

**Comment by zerookiryu15** [comment]
its possible to change the code to have automatic passes?
