### ISSUE TITLE
Add testing sites to README

### ISSUE THREAD

**Issue by Gitoffthelawn** [privacypass/challenge-bypass-extension#22]
It would be great if several testing sites could be added to the README.  By "testing site", I mean sites that always require a CAPTCHA (if this extension is not installed).

Perhaps people can add sites to this issue report, and then the README can be updated with the most consistent testing sites.

**Comment by alxdavids** [comment]
I think this could be a good idea.

**Comment by alxdavids** [comment]
I think this is actually subsumed by #41. The new website will contain a number of domains that test the Privacy Pass functionality.
