### ISSUE TITLE
hCaptcha passes not working

### ISSUE THREAD

**Issue by umerf52** [privacypass/challenge-bypass-extension#224]
**Describe the bug**
As seen in the screenshot, I do have hCaptcha passes but the the [webpage](https://forum.xda-developers.com) is still asking me for captcha.
![image](https://user-images.githubusercontent.com/20578979/113503809-a0ef7480-954d-11eb-9efc-338a32c54721.png)

**To Reproduce**
1. Open https://forum.xda-developers.com

**Expected behavior**
I should be able to visit the website without verifying the captcha if I have passes for the captcha.

**System (please complete the following information):**
 - OS: Microsoft Windows 10 (Version 10.0.19042.867)
 - hCaptcha tokens
 - Browser: Firefox
 - Browser Version: 89.0a1 (2021-04-03) (64-bit)
 - Privacy Pass Version: 2.0.8
 - Add-on installed from Mozilla's add-on store

**Comment by usafety** [comment]
same problem here  its not work anymore

**Comment by armfazh** [comment]
@durch could your team can confirm any recent change in the configuration?

**Comment by joshuamorris23** [comment]
True

**Comment by joshuamorris23** [comment]
> **Describe the bug**
> As seen in the screenshot, I do have hCaptcha passes but the the [webpage](https://forum.xda-developers.com) is still asking me for captcha.
> ![image](https://user-images.githubusercontent.com/20578979/113503809-a0ef7480-954d-11eb-9efc-338a32c54721.png)
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Open https://forum.xda-developers.com
> 
> **Expected behavior**
> I should be able to visit the website without verifying the captcha if I have passes for the captcha.
> 
> **System (please complete the following information):**
> 
> * OS: Microsoft Windows 10 (Version 10.0.19042.867)
> * hCaptcha tokens
> * Browser: Firefox
> * Browser Version: 89.0a1 (2021-04-03) (64-bit)
> * Privacy Pass Version: 2.0.8
> * Add-on installed from Mozilla's add-on store

**Comment by joshuamorris23** [comment]
True

**Comment by ppopth** [comment]
Has you enabled Privacy Pass for your Cloudflare zone?

Actually hCaptcha pass is not meant to be used with Cloudflare captchas (hCaptcha in Cloudflare page as in your figure), so this is an expected behavior.

You can bypass Cloudflare captcha using only Cloudflare passes.

In the figure, you have Cloudflare passes, so you should be able to bypass Cloudflare captchas, and so, I'm curious if you have Privacy Pass enabled for you Cloudflare zone.

You can see if the zone has Privacy Pass enabled by looking if there is a header `cf-chl-bypass: 1` in the response

**Comment by usafety** [comment]
its still not work

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by ppopth** [comment]
It works already in 2.0.9 Sorry for the delayed deployment

**Comment by usafety** [comment]
Still not work and my VPN are very fast, i think you need more API``s for Setting

Sent with [ProtonMail](https://protonmail.com/) secure email.

------- Original Message -------
