### ISSUE TITLE
Privacy Pass not working for current version of browsers

### ISSUE THREAD

**Issue by zydjohnHotmail** [privacypass/challenge-bypass-extension#225]
Before filing a new bug, verify if your request is already being tracked by another issue here: https://github.com/privacypass/challenge-bypass-extension/issues.

--- 

If you believe that this is a new bug, please proceed to create an issue. The issue will be investigated after you have filled in the following information.

**Describe the bug**
A clear and concise description of the bug.

**To Reproduce**
1. Go to 'https://buff.bet/'
2. Click on 'I am human'
3. Scroll down to picture to solve the captcha.

**Expected behavior**
I should get 5 passes, which I can use to avoid solve captcha for 5 more times.

**System (please complete the following information):**
 - OS: Microsoft Windows 10 (Version 10.0.19042.870)
 - Cloudflare tokens or hCaptcha tokens?
 - hCaptcha tokens
 - Browser [e.g. chrome, firefox]
 - Both Chrome and Firefox.
 - Browser Version [e.g. 79, 80, ]
 - Chrome Version 89.0.4389.114 (64-bit)
 - Firefox Version 87.0 (64-bit)
 - Privacy Pass Version [e.g. 2.0.4, 2.0.5 ]
 - 2.0.8
 - Did you install Privacy Pass from this repository or from the browser store?
 - Install from the browser store

**Additional context**

There is one web site, which migrated to use hCaptcha at the end of year 2020.  At the first a few months, I installed Privacy Pass extension for Chrome, it worked. 
However, until rather recently, with the latest version of Chrome Version 89.0.4389.114 (Official Build) (64-bit) and Fire-Fox Version 87.0 (64-bit).
Privacy Pass extension version 2.0.8 stops working any more.
Usually, the first time, when I visit the underlying web site, I have to solve the captcha, then I can get 5 passes, then after exactly 2 hours, the first pass expired; I can simply click on “I am human” button to extend captcha-free time for another 2 hours.
But with the current browsers’ version and current version of privacy pass extension, after 2 hours, I have to manually solve the captcha again.
Please check to verify if you can reproduce the issue.
By the way, if I want to change the extension, now I can get 2.7.0.zip file, so after 2 hours, I want to  automatically click on “I am human” button.  Let me know if it is possible, if yes, give me some general idea how, and provide some guide or reference url.
Thanks,

**Comment by CMDR-Dantae** [comment]
Doesn't work for me either. Hasn't work for over a month now. I do the captcha, and I still have no passes. Weird. Fortunately I had stocked up before, but it's the only way to get Fanfiction net to work these days.

**Comment by RCSWE** [comment]
Same for me - will not work anymore.

**Comment by Chaoschaot232** [comment]
Same for me with Version 101.0.4951.54 (Official Build) (64-bit) for Chrome. Can't get any new Cloudflare Captcha tokens :S
