### ISSUE TITLE
Not working on Brave with private window + TOR

### ISSUE THREAD

**Issue by 7ik1t4** [privacypass/challenge-bypass-extension#229]
I have installed from Chrome Webstore
Chrome version 90 [More info in the image attached]
**It works in the usual Brave browser** but not in the private mode with TOR.

![image](https://user-images.githubusercontent.com/46179582/116813918-f2eae080-ab73-11eb-87b7-4148f53b72bc.png)
![image](https://user-images.githubusercontent.com/46179582/116813949-16ae2680-ab74-11eb-8266-214e21d84813.png)

**Comment by Pyreaus** [comment]
Resolved?

**Comment by 7ik1t4** [comment]
no

**Comment by ppopth** [comment]
I think it works now on the new version 2.0.9
Could you please verify?

**Comment by migueldemoura** [comment]
It has been a while and I'm unable to reproduce the issue, please feel free to reopen if the it persists.
