### ISSUE TITLE
Add support for using captcha backend that distributes open data

### ISSUE THREAD

**Issue by ftyers** [privacypass/challenge-bypass-extension#23]
This is a feature request. At the moment using this requires users to fill out a reCaptcha, where the data that they annotate (mostly image object detection) is not available to them. It would be cool to have a version where the annotated data was made freely available under an open-source/open-data licence so that it could be used by people training free image recognition systems. As a researcher it is a bit frustrating to know that I'm annotating data that I won't have access to.

**Comment by qwerty981** [comment]
norm

**Comment by qwerty981** [comment]
thanks

**Comment by alxdavids** [comment]
Privacy Pass is currently integrated with Cloudflare. However, there is nothing stopping anyone from implementing https://github.com/privacypass/challenge-bypass-server and forking the extension in such a way that what you want is achievable.
