### ISSUE TITLE
Privacy issues

### ISSUE THREAD

**Issue by Maximus778** [privacypass/challenge-bypass-extension#24]
I am not very technical and wasn't sure where I could post this question.

This extension is a great idea. However I was worried whether this extension TECHNICALLY has the ability to transmit the web addresses I surf. For example, when I login to Yahoo, the web address then becomes unique and has a large number of alphanumeric characters which could be used for someone to login to my email.

I am sure no one here has any interest in doing that but I just wanted to understand the technical risks.

Thanks

**Comment by alxdavids** [comment]
The extension aims to never transmit web addresses or any other such browsing information in that way. This sort of information would ultimately deanonymise users which would counteract the claims of the protocol that we use. Moreover, using the URL alone it would be impossible to log in to your personal email without login information or a session cookie.

Hope this helps!
