### ISSUE TITLE
Not working anymore on Firefox v90.0.1

### ISSUE THREAD

**Issue by SpinB** [privacypass/challenge-bypass-extension#243]
Hello,

After updating Firefox to the last version 90.0.1, Privacy Pass Stop working and i can complete the challenge but then i got the error show in the picture on the Console and the tokens are always zero.

 - OS: Windows 10
 - Cloudflare tokens 
 - Browser Firefox
 - Browser Version 90.0.1
 - Privacy Pass Version 2.0.9
 - Browser Store

![pp_error](https://user-images.githubusercontent.com/34115982/126380884-48416a6e-ab11-4807-8b04-690fa348f440.png)

**Comment by naqaden** [comment]
This may not be related to the browser update or browser at all as it has stopped working for me today on Brave and Waterfox Classic, when it was working fine on both yesterday. I see the same errors too.

Solving captchas no longer produces passes and, at least in my case, no longer redirects to the destination. I had to disable the extension to fix the redirect problem for now.

**Comment by SpinB** [comment]
Yeah, i also noted that Cloudflare have a new a challenge maybe that's the reason for the error.

**Comment by SpinB** [comment]
I just updated Firefox to v 90.0.2 and Privacy Pass is working again, problem solved.

**Comment by naqaden** [comment]
Thanks for the update. I checked on my browsers and it's working on Brave and Waterfox Classic again, without updating. I think clearing my cache helped.
