### ISSUE TITLE
[ Site - Not Working ] Bato.to

### ISSUE THREAD

**Issue by 8227846265** [privacypass/challenge-bypass-extension#244]
**Describe the bug**
Whenever you visit bato.to, hCaptcha via Cloudflare appears every single time, even if Privacy Pass is turned on with available tokens.

**To Reproduce**
1. Go to https://bato.to/

**Expected behavior**
The captcha will be automatically be cleared if Privacy Pass has available tokens.

**System (please complete the following information):**
 - OS: 
 Windows 10 x64
 
 - Cloudflare tokens or hCaptcha tokens?
 Both?
 
 - Browser: 
 Brave Browser
 
 - Browser Version:
 Version 1.26.77 Chromium: 91.0.4472.164 (Official Build) (64-bit)
 
 - Privacy Pass Version: 
 2.0.9
 
 - Did you install Privacy Pass from this repository or from the browser store?
 Chrome Web Store

**Comment by firepacket** [comment]
I believe it is possible to require mandatory captcha.

**Comment by ValZapod** [comment]
> hCaptcha via Cloudflare appears every single time, even if Privacy Pass is turned on with available tokens.

It dies not appear here unless Tor is used and even the only after you click on manga, what is less nice is mangago rhat just blick resource, yet if you will try to open those Cloudflare open and if you pass the hCaptcha it will then load resourses.

**Comment by migueldemoura** [comment]
Websites can decide to disable the acceptance of passes from the Privacy Pass extension, see: https://github.com/privacypass/challenge-bypass-extension/issues/105#issuecomment-1155022487
