### ISSUE TITLE
Unexplained error icon

### ISSUE THREAD

**Issue by viliml** [privacypass/challenge-bypass-extension#246]
The Privacy Pass add-on icon always has three red exclamation marks.
What do they mean?
How is the user supposed to try to fix it?
That should be explained somewhere.

**Comment by armfazh** [comment]
This issue was present when hCaptcha support was temporarily paused.
But as of [v3.0.4](https://github.com/privacypass/challenge-bypass-extension/releases/tag/v3.0.4) hCaptcha tokens are enabled again.
Please re-open is this issue continues.
