### ISSUE TITLE
Hpasses not being applied

### ISSUE THREAD

**Issue by bghyt** [privacypass/challenge-bypass-extension#256]
Before filing a new bug, verify if your request is already being tracked by another issue here: https://github.com/privacypass/challenge-bypass-extension/issues.

--- 

If you believe that this is a new bug, please proceed to create an issue. The issue will be investigated after you have filled in the following information.

**Describe the bug**

**To Reproduce**
1. click on the extension in chrome,
2. click HPasses, it will take you to "https://www.hcaptcha.com/privacy-pass"
3. scroll down and do the captcha to earn HPasses
4. No error, just no passes added

**Expected behavior**
click on the extension in chrome, click HPasses, it will take you to "https://www.hcaptcha.com/privacy-pass"
scroll down and do the captcha to earn HPasses

**System (please complete the following information):**
 - OS: Windows 11
 - HCapcha 
 - Browser Chrome
 - Browser Version Version 93.0.4577.82 
 - Privacy Pass Version 2.0.9
 - Google Store

**Additional context**
I've tried the extension for a year+ with the same issue, no updates fixed it for me through windows 10 or 11

**Comment by bghyt** [comment]
here's a video of it too, i installed the extension 20mins before the video & this bus report https://www.youtube.com/watch?v=Qkc_sG5jc9o

**Comment by ValZapod** [comment]
This is fixed by #215.
