### ISSUE TITLE
Unable to Pass StackSkills hCaptcha

### ISSUE THREAD

**Issue by moriel5** [privacypass/challenge-bypass-extension#257]
I have Privacy Pass installed and enabled, topped up with 5 passes, however upon login,  StickSkills is still throwing an hCaptcha prompt, which completing it just reloads the page, and throws another hCaptcha prompt again.

Occasionally, one of my pass is used up, however I still am unable to access my account over in StackSkills.

This is probably an issue with StackSkills and not with the extension, however If thought I put this here, in case there are any logs that may help me troubleshoot this. 

OS: Linux (Solus)
Browser: Firefox 92

**Comment by ppopth** [comment]
Could you please provide the extension version?

**Comment by ppopth** [comment]
It seems like it's the issue of the website's configuration, isn't it? so maybe I can close this issue. If this's still an issue, feel free to reopen

**Comment by moriel5** [comment]
Sorry for the delay, I also think that it's with the websites' configuration, I just tried reaching out to whomever might know what is going on.

If it turn out to be contrary, I'll reopen the issue, however I do not think I'll need to.
