### ISSUE TITLE
cf_clearance cookie is not cleared by the code that should clear it

### ISSUE THREAD

**Issue by ValZapod** [privacypass/challenge-bypass-extension#258]
Before filing a new bug, verify if your request is already being tracked by another issue here: https://github.com/privacypass/challenge-bypass-extension/issues.

--- 

If you believe that this is a new bug, please proceed to create an issue. The issue will be investigated after you have filled in the following information.

**Describe the bug**
A clear and concise description of the bug.
https://captcha.website/ gets a cookie cf_clearance that is supposed to be cleared here: https://github.com/privacypass/challenge-bypass-extension/blob/cb26318d2157e721d97d0436a086156f84b595db/src/ext/listeners.js#L68-L70 Yet it does not work due to new Chrome code.
**To Reproduce**
1. Go to '...' https://captcha.website/
2. Click on '....' captcha
3. Scroll down to '....' solve captcha
4. See error on F5

**Expected behavior**
F5 must open cloudflare's window instead of the actual site.

**System (please complete the following information):**
 - Cloudflare tokens or hCaptcha tokens? 74 and 4
 - Browser [e.g. chrome, firefox] Chrome
 - Browser Version [e.g. 79, 80, ] 94
 - Privacy Pass Version [e.g. 2.0.4, 2.0.5 ] 2.0.9
 - Did you install Privacy Pass from this repository or from the browser store? From Chromium/Chrome store

**Additional context**

**Comment by ppopth** [comment]
This has been fixed in v3.0.0
