### ISSUE TITLE
Version 3.0.0 breaks hCaptcha issuance

### ISSUE THREAD

**Issue by e271828-** [privacypass/challenge-bypass-extension#274]
**Describe the bug**

v2.0.9 Firefox: 

1. visit https://www.hcaptcha.com/privacy-pass
2. solve
3. tokens are issued

v3.0.0 Firefox:

1. visit https://www.hcaptcha.com/privacy-pass
2. "N/A" shown in icon instead of "!!!"
3. no tokens issued on solve

**Comment by GlopGlop31** [comment]
v94.0.1 Firefox

1. visit https://www.hcaptcha.com/privacy-pass
2. "N/A" shown in icon instead of "!!!"
3. no tokens issued on solve

:-(

**Comment by Auncaughbove17** [comment]
you can just install 2.0.9 from [the versions part of the addon page](https://addons.mozilla.org/en-US/firefox/addon/privacy-pass/versions/) and disable auto updates by right-clicking privacy pass, selecting manage extension and setting allow automatic updates to Off.
2.0.9 still works fine.

**Comment by 3xploiton3** [comment]
![image](https://user-images.githubusercontent.com/19517680/141166080-6b0841a9-c512-4724-a4c7-0526da1f5aa7.png)

addon from firefox broken

**Comment by e271828-** [comment]
@ppopth ^

**Comment by ppopth** [comment]
according to the comments https://github.com/privacypass/challenge-bypass-extension/issues/247, there even seems to be an issue with v2.0.9 and I don't know how the Privacy Pass protocol in hCaptcha works yet, so I didn't know how to fix it in v2.0.9 and didn't know how to re-implement it in v3.0.0 as you can see an unimplemented file in https://github.com/privacypass/challenge-bypass-extension/blob/v3-rc/src/background/providers/hcaptcha.ts

it would take me some time to dig into the hcaptcha part of the code in v2.0.9 or it would even be better if hCaptcha can provide the documentation on how their protocol works

**Comment by ReporterX** [comment]
It still broke in my case even if I downgraded to v2.0.9.
Firefox 93.0
"Allow to run in private windows"

1. Visit https://www.hcaptcha.com/privacy-pass
2. Solve
3. No token is issued. "!!!" icon is still shown.

Does anyone know what's wrong?

**Comment by idoi123** [comment]
Hi
Does anyone know when there will be a fix for this issue in the chrome extension version 3.0.0?
Thanks

**Comment by warren-bank** [comment]
fwiw, on Chrome.. I tested both [v2.0.9](https://www.crx4chrome.com/crx/262746/) and v3.0.0 ..identical behavior; hCaptcha didn't work in either (on 2022-01-09).

**Comment by e271828-** [comment]
@warren-bank it works reliably for me with 2.0.9 + Chrome. Your curl failing is probably the desired behavior, since you're effectively trying to reuse tokens.

**Comment by warren-bank** [comment]
for clarity, I'll use the terminology..

to "claim" 5x new tokens is to call:
  `curl 'https://hcaptcha.com/checkcaptcha/...' -X POST --data-raw 'blinded-tokens=...&captcha-bypass=true'`

to "redeem" 1x token is to call:
  `curl 'https://hcaptcha.com/getcaptcha?s=00000000-0000-0000-0000-000000000000' -X POST --data-raw 'v=f9bf301&sitekey=00000000-0000-0000-0000-000000000000&host=www.hcaptcha.com&hl=en&motionData=...&n=...&c=...'`

Interesting that v2.0.9 + Chrome works reliably for you. When I open the extension's "background" page and inspect its network traffic.. the response to "claim" requests nearly always contain a failure message (for "invalid-data") from the server.

Regarding curl, I figured that if a "claim" request does in-fact include correct data that (for some reason) is formatted in a way that the backend refuses to process, that it would be OK to replay (adding/removing parameters, changing content-type from form to json, etc).. since the payload should (presumably) still be valid until properly consumed. Maybe not.. dunno; depends on server-side implementation. In any case, now seeing that it's not an issue of data formatting.. since some requests using the same formatting will randomly succeed.. using curl to test changes to formatting was pointless. Though (thinking out loud).. I'm wondering whether a "claim" request that receives a failed response can be replayed repeatedly (without any change) until it eventually succeeds..

**Comment by warren-bank** [comment]
It would be amusing if it boiled down to something as simple as the choice of charset used for base64 encoding.. since that could explain why sometime it works and sometimes it doesn't.

**Comment by idoi123** [comment]
for me on chrome with  Version 3.0.0 it does not work.
I still see the "N/A" icon on the Privacy Pass extension icon

**Comment by warren-bank** [comment]
funny enough.. I just tested what I had proposed earlier..
1. redeemed the remainder of my 5x hCaptcha tokens so my balance was 0x
2. went to the [page](https://www.hcaptcha.com/privacy-pass) to "earn more passes"
3. solved a captcha to claim 5x more tokens
4. inspected the network tab on the background page to copy the curl command for the failed request.. which it was
5. re-executed the request in curl
  * was planning to replay the request several times until I might eventually receive a successful response
  * only took one try.. received a successful response after only the first replay

so.. it's most definitely a server-side problem.. that returns inconsistent results

**Comment by warren-bank** [comment]
PS: another patch that I would propose.. is that the extension should never redeem a token when the page containing the captcha is equal to the hard-coded URL used to "earn more passes" ..for the particular token type; it would be a very simple string comparison and would enable the ability to earn the max number of tokens allowed

**Comment by warren-bank** [comment]
<details>
  <summary>the following code is only a minor change to the [code used in v2.0.9](https://github.com/privacypass/challenge-bypass-extension/blob/v2.0.9/src/ext/issuance.js#L130-L205)</summary>

  ```javascript
    /**
     * Sends an XHR request containing a BlindTokenRequest for signing a set of tokens
     * @param {Object} xhrInfo XHR info for asynchronous issuance request
     * @param {URL} url URL object
     * @param {Number} cfgId config ID initiating issue request
     * @param {Number} tabId Tab ID for the current request
     * @return {XMLHttpRequest}
     */
    function sendXhrSignReq(xhrInfo, url, cfgId, tabId, retry_counter) {
        const newUrl = xhrInfo["newUrl"];
        const requestBody = xhrInfo["requestBody"];
        const tokens = xhrInfo["tokens"];
        const xhr = new XMLHttpRequest();
        xhr.onreadystatechange = function() {
            // When we receive a response...
            const boundReached = countStoredTokens(cfgId) >= (maxTokens(cfgId) - tokensPerRequest(cfgId));
            if (xhrGoodStatus(xhr.status) && xhrDone(xhr.readyState) && !boundReached) {
                const respData = xhr.responseText;
                // Validates the response and stores the signed points for redemptions
//DIFF:
                try {
                  validateResponse(url, cfgId, tabId, respData, tokens);
                }
                catch(error) {
                  const max_retries = 10;

                  if (
                       (retry_counter >= max_retries)
                    || (!error.json || !(error.json instanceof Object))
                    || ((error.json.success !== false) || !Array.isArray(error.json.error-codes) || (error.json.error-codes.indexOf('invalid-data') === -1))
                  ) throw error;

                  sendXhrSignReq(xhrInfo, url, cfgId, tabId, retry_counter + 1);
                }
            } else if (boundReached) {
                throw new Error("[privacy-pass]: Cannot receive new tokens due to upper bound.");
            }
        };
        xhr.open("POST", newUrl, true);
        xhr.setRequestHeader("Content-Type", "application/x-www-form-urlencoded");
        xhr.setRequestHeader(CHL_BYPASS_SUPPORT, cfgId);
        // We seem to get back some odd mime types that cause problems...
        xhr.overrideMimeType("text/plain");
        xhr.send(requestBody);
        return xhr;
    }

    /**
     * Validates the server response and stores the new signed points for future
     * redemptions
     * @param {URL} url URL object
     * @param {Number} cfgId config ID driving request
     * @param {int} tabId Tab ID for the current request
     * @param {string} data An issue response takes the form "signatures=[b64 blob]"
     * where the blob is an array of b64-encoded curve points
     * @param {Array<Object>} tokens stored tokens corresponding to signed points
     */
    function validateResponse(url, cfgId, tabId, data, tokens) {
        let signaturesJSON;
        switch (signResponseFMT(cfgId)) {
            case "string":
                signaturesJSON = parseSigString(data);
                break;
            case "json":
                signaturesJSON = parseSigJson(data);
                break;
            default:
                throw new Error("[privacy-pass]: invalid signature response format " + signResponseFMT(cfgId));
        }

        if (signaturesJSON == null) {
            throw new Error("[privacy-pass]: signature response invalid or in unexpected format, got response: " + data);
        }

        // creates issueResp object from JSON
        // includes the fields:
        // - signatures
        // - proof
        // - version (optional)
        // - prng (optional)
        const issueResp = parseIssueResp(JSON.parse(signaturesJSON));
        if (!issueResp.signatures) {
//DIFF:
            const error = new Error("[privacy-pass]: No signed tokens provided");
            error.json  = issueResp;
            throw error;
        } else if (!issueResp.proof) {
            throw new Error("[privacy-pass]: No batch proof provided");
        }

        // Validate the received information and store the tokens
        validateAndStoreTokens(url, cfgId, tabId, tokens, issueResp);
    }
  ```
</details>

**Comment by warren-bank** [comment]
regarding a check to prevent redeeming tokens on "get more passes" pages..

<details>
  <summary>the following code is only a minor change to the <a href="https://github.com/privacypass/challenge-bypass-extension/blob/v2.0.9/src/ext/background.js#L353-L380">code used in v2.0.9</a></summary>

  ```javascript
    /**
     * Decides whether to redeem a token for the given URL
     * @param {Object} details Response details
     * @param {URL} url URL object for possible redemption
     * @param {Number} cfgId config identifier
     * @return {boolean}
     */
    function decideRedeem(details, url, cfgId) {
        let attempted = false;
//DIFF:
        if (
             (!spentUrl[url.href])
          && (getMorePassesUrl(cfgId).toLowerCase() !== url.toLowerCase())
        ) {
            const count = countStoredTokens(getConfigId());
            if (doRedeem()) {
                if (count > 0 && !url.host.includes(chlCaptchaDomain())) {
                    attemptRedeem(url, details.tabId, target);
                    attempted = true;
                } else if (count === 0) {
                    // Update icon to show user that token may be spent here
                    updateIcon("!");
                }
            }

            // If signing is permitted then we should note this
            if (!attempted && doSign(cfgId)) {
                setReadyIssue(cfgId, true);
            }
        }
        return attempted;
    }
  ```
</details>

**Comment by aravindvnair99** [comment]
The issue continues in 3.0.2 on Chrome. I get Cloudflare but not hCaptcha.

![image](https://user-images.githubusercontent.com/22199259/161421317-54a0201d-55da-4d24-8f20-ee4e7d0e9f88.png)

**Comment by armfazh** [comment]
As of [v3.0.4](https://github.com/privacypass/challenge-bypass-extension/releases/tag/v3.0.4) support for hCaptcha tokens is re-enabled.
