### ISSUE TITLE
Cannot get tokens in Firefox 94(64-bit)

### ISSUE THREAD

**Issue by R3G3N3R4T0R** [privacypass/challenge-bypass-extension#278]
Happened for quite a while now and I know it is not a global issue as it worked on my Linux machine on Librewolf (a Firefox "fork").

I have absolutely no idea what could have caused it. It actually worked for quite a while before failing, I made a duplicate profile before adding the extension the first time but that too doesn't work right now.
I can also see a lot of negative comments on the addon page saying that it doesn't work for them, so I decided to report it.

### Step to Reproduce
~~1. be me (may actually be important)~~
2. download the extension from [Firefox's addon page](https://addons.mozilla.org/en-US/firefox/addon/privacy-pass/)
3. add click install on the permission pop-up. enable it for private tab or not doesn't matter.
4. go to a cloudflare page or hcaptcha page, doesn't matter.
   - It will display a red box with "0" in it after passing a cloudflare check.
   - It will display a red box with "N/A" in it after passing a hcaptcha check.
5. deny the fact that it doesn't work and try step 4 again, or remove the extension and go back to step 2.

### Expected Behavior
In step 4 instead of displaying a red box, it should be a light blue box with current amount of tokens, 30 for cloudflare and 5 for hcaptcha.

### System Information
Operating System: Windows 10 Pro 21H1 19043.1348
Firefox version: 94.0.2(64-bit) (package maintained by chocolatey)
Privacy Pass version: v3.0.0

**Comment by redegg89** [comment]
Same thing happens to me, so step 1 isn't required. 

Firefox 96.0a1 (64-bit)
Artix Linux w/ kernel 5.15.5-artix1-1
Privacy Pass 3.0.0

**Comment by R3G3N3R4T0R** [comment]
Can confirm, just checked my Librewolf Privacypass version and it was v2.0.9.
Also Artix Linux

**Comment by ppopth** [comment]
Does this happen only in Librewolf? Does it happen also in mainstream Firefox?
I used:
Ubuntu 18.04.6 LTS
Linux 5.4.0-91-generic
Firefox 94.0 (64-bit)
Privacy Pass 3.0.0
and it works

Let me try Librewolf a moment

**Comment by R3G3N3R4T0R** [comment]
My Windows machine is running mainstream FF, which is the one I opened the PR with. So it is a problem in mainstream FF, just that configs may play a role in that too since I have changed some configs in the past years that I don't even remember.

**Comment by ppopth** [comment]
I tried the following machine which is a Virtualbox virtual machine in my linux machine.
Windows 10 Pro Version: 1909 Os build: 18363.778
Firefox 95.0 (64-bit)
Privacy Pass 3.0.0

Please also note that hCaptcha thing doesn't work in v3.0.0 because we decided not to implement it in v3.0.0 and it will only show "N/A", but Cloudflare thing should work fine

**Comment by ppopth** [comment]
Also note that the color is changed to red instead of blue

**Comment by R3G3N3R4T0R** [comment]
Just tested it again on the Windows machine and can confirm Cloudflare is working, The red icon is quite misleading though and it seems that the time lag before the tokens are added made it look like it doesn't work. It is still a nuanced though as I think a lot of people expected hCaptcha to work, but since it will digress from the issue I will close it.
