### ISSUE TITLE
any plans on adding safari variant of the extension

### ISSUE THREAD

**Issue by shengchalover** [privacypass/challenge-bypass-extension#279]
hey 👋

There is closed [thread](https://github.com/privacypass/challenge-bypass-extension/issues/10) here in issues from before Safari adopted WebExtensions in 2020.

Are there still any obstacles? The extension would be quite useful, especially considering that WebExtensions are supported by iOS safari as well since iOS 15.

**Comment by ppopth** [comment]
Thank you for your suggestion. We will keep it into consideration.

**Comment by JOJOforshaun** [comment]
Now, WebExtensions is supported in Safari15, and I also look forward to seeing privacypass on Safari.
