### ISSUE TITLE
hCaptcha + Privacy Pass chrom extension stopped working lately

### ISSUE THREAD

**Issue by idoi123** [privacypass/challenge-bypass-extension#280]
Hi
The hCaptcha privacy pass chrome addon stopped working for me.
It worked great up until a few weeks ago.
I have cleared all cookies, reinstalled the chron extension, tried it on different laptops, nothing helps.

When I solve a captcha instead of seeing new credits in the extension icon I see that "N/A" is displayed in the icon

**Comment by agent255** [comment]
Same issue on firefox

**Comment by idoi123** [comment]
Does anyone know if and when there is a planned fix for this issue?
Thank you

**Comment by FayneAldan** [comment]
I'm having the same issue on Microsoft Edge Dev.

**Comment by FayneAldan** [comment]
Actually, this seems to be a duplicate of #274
