### ISSUE TITLE
Spends too many tokens on promods.net

### ISSUE THREAD

**Issue by erkinalp** [privacypass/challenge-bypass-extension#281]
Browser: Firefox 96 Beta
Steps to reproduce: visit promods.net
Expected: Spend 1 token per visit, or a few per session
Actual: Spends 21 tokens per page, and ignores the amount of tokens while presenting captcha

**Comment by ppopth** [comment]
Could you please provide the Extension version?

**Comment by erkinalp** [comment]
v3.0

**Comment by erkinalp** [comment]
consumes 124 tokens per session now

**Comment by armfazh** [comment]
@erkinalp please (re-)open a ticket if you still see an issue.
