### ISSUE TITLE
hCaptcha Website doesnt work

### ISSUE THREAD

**Issue by AngerminecraftYT** [privacypass/challenge-bypass-extension#286]
i got over to the hCaptcha site to receive hCaptcha Passes but it didnt work

**Info:**
OS: Windows 11
Browser: Google Chrome (Latest Version)
Type of Device: PC
Extention from Github or Web Store: Webstore
**Expected:**
It would give me the hCaptcha Pass

**Reality:**
Didnt give me hCaptcha Passes it just says N/A

(i completed the captcha too btw)

**Comment by vezycash** [comment]
Same happens on firefox.

**Comment by CPTProgrammer** [comment]
Me too.

**Comment by Xane123** [comment]
I'm having the same problem in my Firefox. Looking at the console, at least a few errors appear the moment the captcha is completed:

`This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://firefox-source-docs.mozilla.org/performance/scroll-linked_effects.html for further details and to join the discussion on related tools and features! privacy-pass`

`Content Security Policy: Ignoring “'self'” within script-src: ‘strict-dynamic’ specified`

`Content Security Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified`

`Content Security Policy: Ignoring “https:” within script-src: ‘strict-dynamic’ specified`

**Comment by ppopth** [comment]
Duplicated of #274
