### ISSUE TITLE
Cloudflare Passes completely broken

### ISSUE THREAD

**Issue by RealDolos** [privacypass/challenge-bypass-extension#291]
The reason for this seems simple: you (cloudflare) rolled out a new version of the captcha challenge that broke your (privacy pass) extension.

E.g. the extension looks for POSTs with `__cf_chl_captcha_tk__'  or '__cf_chl_managed_tk__` to detect a challenge submission ([see](https://github.com/privacypass/challenge-bypass-extension/blob/6c0c3a80eb46878a6629de12c61aac4fc180ea5c/src/background/providers/cloudflare.ts#L240)). But requests with these parameters do not exist anymore. The closest is `__cf_chl_rt_tk`, but that one isn't even used in the POST itself, it's just pushed onto the browser history when that challenge js is loaded and replaced again afterwards. The final submission POST cannot be detected that way, and the extension will therefore never even attempt to do an issuance.

Tested broken: Firefox and Chrome (no surprise), extension version 3.0.0

**Comment by ppopth** [comment]
#292 for tracking

**Comment by mendelsphotography** [comment]
By me had the same issue but seemed to be by me it screwed up the CSS but if used in Incognito it was fine and as soon I disabled the extension (privacy pass) soo don't know if that's related also or just me

**Comment by ppopth** [comment]
This has been resolved in v3.0.1
