### ISSUE TITLE
Dos this not work with Edge?

### ISSUE THREAD

**Issue by rolltidehero** [privacypass/challenge-bypass-extension#297]
I can't get it to credit me any passes when using Edge on captcha.website.

Can anyone confirm that it works with Edge or not, or if this is just related to issue #293

**Comment by armfazh** [comment]
Currently no explicit support is given for Edge. We are looking for making it available.

**Comment by moriel5** [comment]
I personally have no issues as a result of using Privacy Pass on Microsoft Edge.

If anything, I am having issues reliably packaging Microsoft Edge for Solus (the Linux distro I am currently using).

**Comment by armfazh** [comment]
Although no explicit support, it works (for me), just follow the instructions at 
https://github.com/privacypass/challenge-bypass-extension#edge
to install the extension in Edge.
