### ISSUE TITLE
npm test (Build) Doesnt work propettly

### ISSUE THREAD

**Issue by AngerminecraftYT** [privacypass/challenge-bypass-extension#298]
ive done first: npm ci then: npm test

(As instructed)

Logs:
> cd node_modules/sjcl && ./configure --without-all --with-ecc --with-convenience --with-codecBytes --with-codecHex --compress=none && make sjcl.js

'.' is not recognized as an internal or external command,
operable program or batch file.

Please help me.

**Comment by armfazh** [comment]
try to run commands manually.
make sure you have a folder named `node_modules/sjcl`
These instructions are for running on a linux system, commands may not work on a windows system.

**Comment by warren-bank** [comment]
`configure` is a perl script.. do you have perl installed?
* as written, it requires the `strict` cpan module;<br>the line that imports this module can be removed/commented.. if need be
* the "sjcl" npm script is written in such a way that it would only successfully run in a shell that inspects scripts for a _shebang_ line; it would be better (ie: more cross-platform) to rewrite `./configure` as `perl configure`
