### ISSUE TITLE
Privacy Pass Version 3.0.1 Doesn't work

### ISSUE THREAD

**Issue by 3xploiton3** [privacypass/challenge-bypass-extension#299]
Chrome Dev Latest Update

**Comment by 3xploiton3** [comment]
![Privacy_Pass_-_Google_Chrome_19-02-2022-(-)](https://user-images.githubusercontent.com/19517680/154790142-b51f80b1-0099-4578-a74e-319893bc8c48.gif)

**Comment by szpak** [comment]
I observe similar behavior with 3.0.1 and Firefox 97.

**Comment by MisterT87** [comment]
+1 v3.0.1 on Firefox 97.0.1

**Comment by moriel5** [comment]
I can attest to the same on Firefox 97 on Linux (Solus).
CloudFlare passes appear to work fine, however hCaptcha do not.

**Comment by Scratch-net** [comment]
Same for Chrome and Version 3.0.2

**Comment by rtunazzz** [comment]
Having a similar issue on Brave since version 3.0.0 (currently on 3.0.2 and issue still persist)

It's possible to get Cloudflare passes but hCaptcha passes stay at 0 while extension badge shows `N/A`

**Comment by SynergyBest** [comment]
> Having a similar issue on Brave since version 3.0.0 (currently on 3.0.2 and issue still persist)
> 
> It's possible to get Cloudflare passes but hCaptcha passes stay at 0 while extension badge shows `N/A`

Having the exact same issue as rtunazzz on `Version 1.35.103 Chromium: 98.0.4758.102 (Official Build) (64-bit)`

**Comment by SynergyBest** [comment]
Just updated to `Version 1.36.109 Chromium: 99.0.4844.51 (Official Build) (64-bit)` the issue persists.

**Comment by moriel5** [comment]
It's interesting how hCaptcha passes currently don't get added and are otherwise unfunctional on both Firefox and Chromium browsers, however on Firefox the hCaptcha icon remains at zero, while on Chromium browsers it turns into N/A.

**Comment by ambrt** [comment]
Same here. v3.0.2 Firefox 98.0.1

**Comment by vedkothavade** [comment]
+1, Cloudflare working just fine but hCaptcha shows N/A.
Brave version 1.36.116, Chromium: 99.0.4844.74

**Comment by aravindvnair99** [comment]
The issue continues in 3.0.2 on Chrome. I get Cloudflare but not hCaptcha.

![image](https://user-images.githubusercontent.com/22199259/161421317-54a0201d-55da-4d24-8f20-ee4e7d0e9f88.png)

**Comment by armfazh** [comment]
support for hCaptcha is on standby until further notice.

**Comment by migueldemoura** [comment]
A notice has been added to the README explaining this, see: https://github.com/privacypass/challenge-bypass-extension#user-content-hcaptcha-support.

**Comment by moriel5** [comment]
@migueldemoura Thanks, although after looking at it, it appears that nothing is explained, only the fact that support for hCaptcha had been payed is pointed out.

Is there some technical information that can be brought as an explanation?

**Comment by prettyv** [comment]
I agree, this doesn't read like much of an explanation to me either. Given the gradual disappearance of Cloudflare CAPTCHAs (see https://blog.cloudflare.com/end-cloudflare-captcha/, my respective 30 Cloudflare tokens/passes haven't seen any use since I last collected them a long time ago), and now hCaptcha not being supported anymore this extension doesn't really serve much of a practical purpose any more AFAICS.

Are there any plans to reintroduce hCaptcha support in some future version? It seems to me the reasons aren't necessarily technical, please correct me if I'm wrong.
