### ISSUE TITLE
How to conserve passes

### ISSUE THREAD

**Issue by Youms** [privacypass/challenge-bypass-extension#30]
I have configured firefox so as to clear all cookies upon exit. Is that why i can't kepp any pass i have once generated? Great extension though.

**Comment by alxdavids** [comment]
We had problems with this ourselves. The tokens are stored in localstorage, maybe when you clear cookies you are also clearing this?

**Comment by Youms** [comment]
Any way it doesn't work on my browser, hasn't been updated for long and now it does not bypass any challenge.
