### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by Nothanks777777** [privacypass/challenge-bypass-extension#300]
Every time I attempt to install the program I get thrown up this error. Any help would be sick. 
![image](https://user-images.githubusercontent.com/84105940/153715182-80fcb2e3-5c70-4f74-8c6d-e05c98ea69f5.png)

**Comment by warren-bank** [comment]
1) the npm scripts don't "install" the chrome extension.. they build a directory that can be packed into a chrome extension
2) `configure` is a perl script.. do you have perl installed?
   * as written, it requires the `strict` cpan module;<br>the line that imports this module can be removed/commented.. if need be

**Comment by Deyrap355** [comment]
What do I need to do? I'm confused

**Comment by warren-bank** [comment]
@Deyrap355 

```bash
git pull origin master

npm run clean
npm run build
```

* if you have `perl` and `make` in `PATH`,<br>then "sjcl" should build without any errors
* `./dist` directory should exist and contain an unpacked webextension,<br>which you can install in your web browser for testing,<br>or use your web browser to pack into a self-signed extension
