### ISSUE TITLE
Missing changelog/release notes for 3.0.x in GitHub releases

### ISSUE THREAD

**Issue by szpak** [privacypass/challenge-bypass-extension#309]
The GitHub release page for the project shows 2.0.9 as the latest version:

![image](https://user-images.githubusercontent.com/148013/154818986-5d83ca75-a4d6-4110-9ca8-bba435f5e812.png)

It would be good to have it updated with 3.0.x (currently there are only tags), also with the changelog (which doesn't seem to be provided also in any file in the repository).

**Comment by warren-bank** [comment]
+1 for add back the [LICENSE](https://github.com/privacypass/challenge-bypass-extension/blob/v2.0.9/LICENSE)

**Comment by armfazh** [comment]
Solved now by #322

**Comment by szpak** [comment]
Thanks @armfazh .
