### ISSUE TITLE
hCaptcha 3.0.2 doesn't work in chrome dev

### ISSUE THREAD

**Issue by 3xploiton3** [privacypass/challenge-bypass-extension#310]
![gif](https://i.imgur.com/gkDj8Es.gif)

**Comment by coddest** [comment]
i have the same problem, it used to work but now i can't get new passes

**Comment by Alexey71** [comment]
FireFox also not working

**Comment by LadyGrelka** [comment]
Same problem with both hCaptcha and Cloudflare on Firefox

**Comment by ninjaeon** [comment]
hCaptcha not working in Chrome Official (99.0.4844.82 as of this post) using Privacy Pass Extension 3.0.2

**Comment by aravindvnair99** [comment]
Does not work on Chrome stable as well. I get Cloudflare but not hCaptcha.

![image](https://user-images.githubusercontent.com/22199259/161421317-54a0201d-55da-4d24-8f20-ee4e7d0e9f88.png)

<html>
<body>


Google Chrome | 100.0.4896.60 (Official Build) (64-bit) (cohort: Stable Installs & Version Pins)
-- | --



</body>
</html>
<html>
<body>


OS | Windows 11 Version 21H2 (Build 22000.593)
-- | --



</body>
</html>

# Related / similar open issues:
- #274
- #299
- #306

**Comment by lmtr0** [comment]
Any status on this?

**Comment by armfazh** [comment]
support for hCaptcha is on standby until further notice.

**Comment by migueldemoura** [comment]
@armfazh can we get a notice in the README or maybe even removal of the hCaptcha option while it's not functional in v3?

**Comment by lmtr0** [comment]
is it working on older versions?

**Comment by migueldemoura** [comment]
Closing since the notice that hCaptcha isn't supported in versions 3.x.x has been added to the README: https://github.com/privacypass/challenge-bypass-extension#user-content-hcaptcha-support.

**Comment by txtsd** [comment]
> Closing since the notice that hCaptcha isn't supported in versions 3.x.x has been added to the README: [privacypass/challenge-bypass-extension#user-content-hcaptcha-support](https://github.com/privacypass/challenge-bypass-extension#user-content-hcaptcha-support).

@migueldemoura Is there a reason hCaptcha support has been paused?

**Comment by BTCAlchemist** [comment]
The ReadMe says
> hCaptcha support
> As of version 3.0.4, support for hCaptcha tokens has been re-enabled. Note: even though an hCaptcha captcha consumes one token from the extension, it is still possible that the user must solve an interactive captcha. This behaviour depends on the logic used by the captcha provider, and does not indicate a malfunctioning of the PrivacyPass extension.

@armfazh This is happening to me in which a token is consumed from the extension, but I still have to solve the captcha challenge. How is it that a captcha provider may use logic that would bypass the PrivacyPass extension? Could any further development work mitigate this? Thanks in advance.
