### ISSUE TITLE
Your Evil Tyranny 

### ISSUE THREAD

**Issue by Walters-Marissa** [privacypass/challenge-bypass-extension#314]
https://www.zdnet.com/article/cloudflare-wants-to-kill-the-captcha/
You all should be ashamed of yourselves, but I know you are all inhuman people who do not respect user choice, and have broken captcha on your site to herd users into this new paradigm of yours. You will not feel a drop of shame, nor fix the issues you have deliberately caused that have cut me off of such dangerous websites as _onlineclock.net_. **No, I will not take your fake panacea handed out to cure a problem you yourself created.** 

Allow users to once again complete CAPTCHA, or you can look forward to parallel systems developing in the absence of your humanity.

**Comment by firepacket** [comment]
> _"...each hardware key shares its identifier with other keys manufactured in the same batch. From Cloudflare's perspective, your key looks like all other keys in the batch."_

Wow, they are geniuses! That is definately going to work.

Let's replace a turing-test with an automated **_NON-TURING_**-test that can easily be used by bots, AS WELL AS uniquely identifying you everywhere you go! Sounds fantastic!  :tada: :partying_face: :fireworks:

**Comment by thibmeu** [comment]
This issue is not actionable, and not constructive. I'm closing it. Feel free to open one using the provided template if there are specific actions to be taken, or changes you would like to push through
