### ISSUE TITLE
Cloudflare issuance broken once more

### ISSUE THREAD

**Issue by RealDolos** [privacypass/challenge-bypass-extension#317]
Broken on Firefox at least

Seems this time cloudflare will just ignore the issuance request and redirect back to / (which is then 403, and `CloudflareProvider.issue()` bails when it sees that response, of course).

It's almost like the cloudflare captcha people still do not talk to the extension people...

@ppopth is good at fixing these :D

**Comment by armfazh** [comment]
we are investigating this issue. thanks for reporting.

**Comment by RLBROWN96** [comment]
How long does a error like this normally take you guys to rectify btw? also is there somewhere you guys take donations? would like to donate to the cause!

**Comment by armfazh** [comment]
No changes were needed in the extension.
CF experienced some issues [last week](https://www.cloudflarestatus.com/incidents/f6cv9cxtfdj2). Solved now.
