### ISSUE TITLE
I'm getting "!!!" and no passes

### ISSUE THREAD

**Issue by GGGunrunner** [privacypass/challenge-bypass-extension#32]
Its Firefox 52 on Win. 

I solve the challenge, but getting "!!!" (white on red).

PS: What is the lowest supported FF version? Have a few old machines with FF 47, it doesnt seem to install at all. Can this restriction be lifted?

**Comment by m0n5t3r** [comment]
well, captcha.website seems dead now, so this is either abandoned or they got kicked off internet's MITM-in-chief, a.k.a. cloudflare

**Comment by alxdavids** [comment]
Hi, sorry I've been a little busy recently so haven't had much time to check these issues out. Indeed captcha.website does seem to be down right now so I'll look into that, thanks for alerting me!

You should still be able to fill up your passes via a Cloudflare domain that servers CAPTCHAs in the meanwhile.

**Comment by alxdavids** [comment]
captcha.website is back up and running now.
