### ISSUE TITLE
get more passes Not working 

### ISSUE THREAD

**Issue by dreamboxgate** [privacypass/challenge-bypass-extension#335]
Hello there 
I am trying to get more passes from privacypass extention using windows/chrome Version 102.0.5005.63
It is there anything wrong , or a bug .
When i ask for passes
I complete security check 
redirected to https://captcha.website/
But i didn't get any pass 

Thanks

**Comment by Kippersz** [comment]
Looks like it broke again as I needed to get more tokens for passes...

**Comment by dreamboxgate** [comment]
nothing changed 
can't get more passes 
Chrome is up to date
Version 102.0.5005.115
