### ISSUE TITLE
Browser freezes with multiple tabs are loaded

### ISSUE THREAD

**Issue by ballsystemlord** [privacypass/challenge-bypass-extension#34]
Hello,
I am running FF 62.0. I tried to load 40 pages from my local HD. I was looking for something. The whole browser froze for more than 10min running 100CPU on 2 cores (I have 6).
1: I killed FF, restarted, set FF to offline mode, and restored my session with the same result 3 times.
2: I then disabled all add-ons and did 1 and everything loaded almost instantly.
3: I then enabled each addon in succession until I noticed a massive slow down.
I found 2 addons were causing the freeze.
Yours is one of them. I have no idea why. I cannot even imagine because it is supposed to allow me to pass into websites, but I was not even online!
I would be happy to provide any additional necessary information.
```
% uname -a
Linux Phenom-II-x6 4.17.8dav1 #5 SMP PREEMPT Thu Aug 9 03:50:23 UTC 2018 x86_64 GNU/Linux
```
Thanks!

**Comment by alxdavids** [comment]
Okay that is interesting, thanks for alerting us to it. I'll have a look into it. Have you tried to see if the same thing happens with Chrome by any chance?

**Comment by ballsystemlord** [comment]
On Sun, 23 Sep 2018 11:11:57 -0700
alex <notifications@github.com> wrote:
> Okay that is interesting, thanks for alerting us to it. I'll have a
> look into it. Have you tried to see if the same thing happens with
> Chrome by any chance?
> 

No, I try not to use Google's stuff. They have been caught spying on
email users and including binary instead of source data in chrome.

Thanks

**Comment by alxdavids** [comment]
It would be interesting to see if this occurs with the current master branch, will try to look into this soon.

**Comment by alxdavids** [comment]
There have been no reports of this for a long time and I haven't been able to reproduce. Please re-open if it is still an issue with the current version of the extension.
