### ISSUE TITLE
No passes issued on TOR browser

### ISSUE THREAD

**Issue by mojo-jojo-7** [privacypass/challenge-bypass-extension#342]
**Describe the bug**
I get no passes after solving the captcha on https://captcha.website/ when on TOR browser

**How to reproduce**
1. Go to https://captcha.website/
2. Solve the captcha
3. Check the pass counter in extension pop-up

**Expected behavior**
Should get 30 cloudflare passes

**System (please complete the following information):**
 - OS: Windows 10
 - Cloudflare tokens or hCaptcha tokens? Cloudflare
 - Browser: TOR
 - Browser Version: 11.5.1
 - Privacy Pass Version: 3.0.3

**Additional context**
It's working fine on Firefox. This is my first time using this extension, so I don't know if this is an old bug, but I see no active issue specific to TOR browser

**Comment by ziproot** [comment]
Main issue: #337
