### ISSUE TITLE
n/a over privacy pass when going to curseforge website

### ISSUE THREAD

**Issue by frakier** [privacypass/challenge-bypass-extension#346]
**Describe the bug**
n/a over privacy pass on curseforge site promps with a CAPTCHA, that then promps with a CAPTCHA, that then promps with a CAPTCHA, that then promps with a CAPTCHA, that then promps with a CAPTCHA, that then promps with a CAPTCHA...
You never reach the website...

**How to reproduce**
self expalnatory

**Expected behavior**
get into the website automatically because I have token on the privacy pass

**System (please complete the following information):**
 - Win 10
 - Cloudflare tokens
 - Firefox
 - Browser Version 104.0.1 (64-bit)
 - Privacy Pass Version 3.0.3

**Comment by migueldemoura** [comment]
Hi @frakier, can you attach a HAR file of these requests and attach it here? Feel free to redact cookies or other sensitive information applicable to "curseforge".

**Comment by armfazh** [comment]
@frakier please update to [v3.0.4](https://github.com/privacypass/challenge-bypass-extension/releases/tag/v3.0.4), this error seems to be related to the lack of support of hCaptcha tokens.
