### ISSUE TITLE
Recaptcha is not getting solved with 30 passes

### ISSUE THREAD

**Issue by dunnodun** [privacypass/challenge-bypass-extension#35]
Thanks for the great work. Sadly I couldn't get it to work with Recaptcha. 
I solved the initial Recaptcha and got 30 passes but if I'm visiting other sites with a Recaptcha I still have to solve the challenges. 
Am I misinterpreting this extension and it's not possible with Recaptcha or is that a general problem?

**Comment by gidoBOSSftw5731** [comment]
This is only for cloudflare prompts from using TOR/VPNs ([captcha.website](captcha.website))

**Comment by dunnodun** [comment]
I was hoping for something that helps me to bypass the annoyance of Recaptcha with VPN :( Doesn't seem to exist.
Thanks for the clarification :)
