### ISSUE TITLE
privacypass 3.0.4 doesn't work on reports.adguard.com

### ISSUE THREAD

**Issue by 3xploitzer0** [privacypass/challenge-bypass-extension#353]
![image](https://user-images.githubusercontent.com/56762704/204073786-33157e0b-6bdc-4c78-af53-d5e8da438472.png)

example:
[https://reports.adguard.com/en/new_issue.html?browser=Chrome&browsing_security.enabled=true&filters=14.17.1.224.2.3.7.105.120.18.19.21.22.122&product_type=Ext&product_version=4.1.46&stealth.enabled=false&url=https%3A%2F%2Fmanhwaindo.me%2Fmanga%2Fmy-stepmother-is-my-girlfriend%2F](url)

**Comment by 3xploitzer0** [comment]
https://td.msgsuite.workers.dev/

didn't work

**Comment by thibmeu** [comment]
We've provided an update in https://github.com/privacypass/challenge-bypass-extension/issues/400. I'm closing this ticket as duplicate.
