### ISSUE TITLE
No passes issued on TOR browser

### ISSUE THREAD

**Issue by mojo-jojo-7** [privacypass/challenge-bypass-extension#381]
**Describe the bug**
I get no passes after solving the captcha on https://captcha.website/ when on TOR browser

**How to reproduce**
1. Go to https://captcha.website/
2. Solve the captcha
3. Check the pass counter in extension pop-up

**Expected behavior**
Should get 30 cloudflare passes

**System (please complete the following information):**
 - OS: Windows 10
 - Cloudflare tokens or hCaptcha tokens? Cloudflare
 - Browser: TOR
 - Browser Version: 11.5.8
 - Privacy Pass Version: 3.0.4

**Additional context**
I could not re-open my [old issue](https://github.com/privacypass/challenge-bypass-extension/issues/342) about the same thing, so I'm creating a new one instead

**Comment by ericpa06** [comment]
I think it's the same issue here, since TOR uses firefox as basis:
https://github.com/privacypass/challenge-bypass-extension/issues/362

**Comment by thibmeu** [comment]
We've provided an update in https://github.com/privacypass/challenge-bypass-extension/issues/400. I'm closing this ticket as duplicate.
