### ISSUE TITLE
hCaptcha not work again

### ISSUE THREAD

**Issue by Mishasama** [privacypass/challenge-bypass-extension#384]
Before reporting a new bug, verify if your request is already being tracked by another issue: https://github.com/privacypass/challenge-bypass-extension/issues.

---

If you believe that this is a new bug, please proceed to create an issue. The issue will be investigated after you have filled in the following information.

**Describe the bug**
A clear and concise description of the bug.
https://addons.mozilla.org/en-US/firefox/addon/privacy-pass/reviews/1895027/
It will cause keeping a loop at hCaptcha.

**How to reproduce**
1. Go to Discord
2. Try to login or join any channel
3. Solve the hCaptcha

**Expected behavior**
A description of what is expected to happen.
It should bypass the hCaptcha. Or just act like without privacypass.

**System (please complete the following information):**
 - OS: Windows
 - hCaptcha tokens
 - Browser firefox
 - Browser Version 108
 - Privacy Pass Version 3.0.4

**Additional context**

**Comment by thibmeu** [comment]
hCaptcha [announced](https://www.hcaptcha.com/privacy-pass) the end of their support for the legacy Privacy Pass protocol in favor of the IETF version.

I'm closing this ticket.
