### ISSUE TITLE
captcha.website no longer providing Passes

### ISSUE THREAD

**Issue by SteveBox0** [privacypass/challenge-bypass-extension#386]
**Describe the bug**
Clicking on Cloudflare and verifying your are human, no longer provides passes. I have tested this in both Firefox and chrome for captcha.website on multiple machines. 

**How to reproduce**
1. Go to extension icon and click on Cloudflare
2. Plugin goes to https://captcha.website/
3. Verify your are human
4. After solving the website redirects to https://captcha.website/ but load a broken version of https://privacypass.github.io/

**Expected behavior**
Adds additional passes that can be used later.

**System (please complete the following information):**
 - OS: Windows
 - Cloudflare tokens
 - Browser Chrome 109.0.5414.120 and Firefox 111.0a1
 - Privacy Pass Version 3.0.4

**Comment by ring0jke** [comment]
I have the same issue on that. Please help :(

**Comment by armfazh** [comment]
we identified an issue, we will release soon an update.

See https://github.com/privacypass/challenge-bypass-extension/pull/387

**Comment by armfazh** [comment]
New version has been published in Firefox and Chrome stores.

**Comment by 3xploiton3** [comment]
> we identified an issue, we will release a new version soon.
> 
> Fix: #387
> 
> Status: https://www.cloudflarestatus.com/incidents/r5b15yx8l78l

issue still remain at v3.0.5 using chrome stable

**Comment by neoxedneox** [comment]
I can confirm that this is still happening at v3.0.6. After solving i'm redirected to https://privacypass.github.io/
