### ISSUE TITLE
Extention does not use tokens to bypass verifiration [Cloudflare].

### ISSUE THREAD

**Issue by BogudanPro** [privacypass/challenge-bypass-extension#389]
Before reporting a new bug, verify if your request is already being tracked by another issue: https://github.com/privacypass/challenge-bypass-extension/issues.

---

If you believe that this is a new bug, please proceed to create an issue. The issue will be investigated after you have filled in the following information.

**Describe the bug**
Maybe I'm just stupid and don't understand how extention intended to work, but...
Extention does not use tokens to bypass Cloudflare verification.

**How to reproduce**
My steps are following:
1. Install addon
2. Get some cloudflare tokens (now i've red "30" on extention icon)
3. Go to https://www.scribblehub.com/ (now extention icon is gray without numbers)
4. Get capcha request ("verify you are human", any of 2 versions).
4.1. Clicking button goes into infinite looping animation (same was happening before extention was installed as result of disabling web workers).

**Expected behavior**
Use tokens to bypass check.

**System (please complete the following information):**
 - OS: Linux Mint 20.3
 - Cloudflare tokens
 - Browser FF 101.0 (x64)
 - Privacy Pass 3.0.5

**Additional context**
Web workers were disabled using uBO with rule `*$csp=worker-src 'none'`
ETP set to custom (disabling it for problem site didn't solved issue):
* cookies: disable all 3rd-party cookies
* tracking content: all windows
* cryptominers
* fingerprinters

**Comment by ericpa06** [comment]
This! I thought I was crazy, but it simply doesn't seem to be working, like straight out not working. I tested in several browsers and it is the same result...

**Comment by BogudanPro** [comment]
> This! I thought I was crazy, but it simply doesn't seem to be working, like straight out not working. I tested in several browsers and it is the same result...

Can I assume that you don't disable workers in your browsers?

**Comment by wezlol** [comment]
Same here; both are not working. However, hCaptcha gets +5 when solving a captcha, and -1 when opening a new one.

**Comment by frjoethesecond** [comment]
I'm having this problem too recently. I changed settings to improve security such as blocking fingerprinting and using account containers. I wonder if this addon needs fingerprinting in order to work?

**Comment by thibmeu** [comment]
Closing this issue in favor of https://github.com/privacypass/challenge-bypass-extension/issues/400, where a major reshape is being centralised to support IETF version.
