### ISSUE TITLE
captcha.website requires third-party storage access

### ISSUE THREAD

**Issue by ilf** [privacypass/challenge-bypass-extension#395]
**Describe the bug**
Tor Browser cannot visit https://captcha.website/ because it requires third-party storage access

**How to reproduce**
1. Go to https://captcha.website/
2. Verify
3. See error

> Request to access cookie or storage on "<URL>" was blocked because we are blocking all third-party storage access requests and content blocking is enabled.
> Learn more: https://developer.mozilla.org/en-US/docs/Web/Privacy/Storage_Access_Policy/Errors/CookieBlockedForeign

**Expected behavior**
Visit https://captcha.website/

**System (please complete the following information):**
 - OS: Linux
 - Cloudflare tokens
 - Browser: Tor Browser
 - Browser Version: 12.5
 - Privacy Pass Version: 3.0.5

**Additional context**

**Comment by 3xploiton3** [comment]
![image](https://github.com/privacypass/challenge-bypass-extension/assets/19517680/a45f4f76-3682-44a7-9397-e0d252d57c20)

**Comment by thibmeu** [comment]
The website indeed seems to try setting a third party cookie which is rejected by Tor browser (13.0.7) given its default cookie policy.

However, this does not preclude the website from being accessed, and is more related to captcha.website policy than Privacy Pass specifically.

**Comment by ilf** [comment]
@thibmeu I do not agree with closing this issue.

Maybe the third-party cookie is not the original problem causing the issue.

But the issue is still valid: Current Tor Browser cannot visit https://captcha.website/ and therefore cannot obtain tokens, thus making challenge-bypass-extension useless.

**Comment by thibmeu** [comment]
Using Tor Browser 13.0.7, captcha.website is accessible, and redirects to privacypass.github.io as expected. See the joined 
[HAR](https://github.com/privacypass/challenge-bypass-extension/files/13743127/captcha.website.har.zip), leading to the ![following page](https://github.com/privacypass/challenge-bypass-extension/assets/1894894/d693fa62-8e70-485d-b68c-6c120959160f) once redirected.
The third party cookie is not required, but requested. The issue being titled "captcha.website requires third-party storage access", it has been closed.

Regarding the obtention of tokens, this is an other issue, linked to the upgrade of Privacy Pass protocol. It is being tracked in #400. You should feel free to add comment on that ticket.

**Comment by ilf** [comment]
https://captcha.website/ is still not accessible and does not redirect to https://privacypass.github.io/ in my Tor Browser 13.0.8.

But there's already an issue for that: #277.
