### ISSUE TITLE
Add ability to transfer tokens

### ISSUE THREAD

**Issue by atoponce** [privacypass/challenge-bypass-extension#4]
While this extension reduces the amount of work an honest Tor user will need to perform on Cloudflare sites, there are still honest users where this extension doesn't meet their needs:

* Visually impaired who cannot solve visual captchas
* Non-native English speakers who cannot solve the audio captcha.
* Browsers without JavaScript, such as some screen readers, or where JavaScript is disabled, such as in some corporate policies.

So my issue is this- the extension needs the ability to transfer tokens. I can solve the captchas, then send the tokens to a visually impaired user, so he/she can access the Cloudflare site while on Tor without needing to worry about the captcha problem.

**Comment by atoponce** [comment]
A possible solution could be a centralized repository, where users do the proof-of-work solving the captchas, then the extension can upload tokens to a website, where others can download them into their extension. Something like https://privacytokens.website perhaps.

**Comment by oliverpool** [comment]
But then you have to be sure that this "central website" only forwards the token to actual users (and does not use it for malicious purposes or forward it to bots)

**Comment by atoponce** [comment]
Yeah. A centralized web site of privacy-preserving credentials probably isn't such a hot idea after thinking it through. But still having the ability to send them to users who can't solve the captchas is key. Email, Signal, USB, whatever.

**Comment by alxdavids** [comment]
Yeah we want to avoid centralising tokens as it could be abused to create large stockpiles that could be used by bots etc. 

I agree that for cases where it is difficult for a user to interact with a browser then it may be useful for a trusted person to perform authentication on their behalf and then send tokens via some sort of direct message. We will probably have to have a discussion regarding what sort of method will be best.

**Comment by alxdavids** [comment]
This is not something that is being looking into currently, but I will re-open if this changes.
