### ISSUE TITLE
No passes are provided

### ISSUE THREAD

**Issue by neoxedneox** [privacypass/challenge-bypass-extension#401]
Describe the bug
After clicking on "verifying your are human" you are redirected to main page. I've also tested this in Firefox and Chrome on different machines.

How to reproduce

    Go to extension icon and click on Cloudflare
    Plugin goes to https://issuance.privacypass.cloudflare.com/
    Verify you are human
    After solving the website redirects to https://privacypass.github.io/

Expected behavior
Adds additional passes.

System:

    OS: Windows
    Cloudflare tokens
    Browser Chrome 116.0.5845.188 and Firefox 117.0.1
    Privacy Pass Version 3.0.6

**Comment by armfazh** [comment]
An issue on the service has been identified. A major reshape of the extension is in progress.

**Comment by neoxedneox** [comment]
Will it take a long time to be fixed ?

**Comment by gamersindo1223** [comment]
> An issue on the service has been identified. A major reshape of the extension is in progress.
Is there any Estimated Time when will the extension could be used again

**Comment by thibmeu** [comment]
We've provided an update in #400. I'm closing this ticket as duplicate.
