### ISSUE TITLE
Doesn't do anything on edge

### ISSUE THREAD

**Issue by cyber-sec0** [privacypass/challenge-bypass-extension#407]
Before reporting a new bug, verify if your request is already being tracked by another issue: https://github.com/privacypass/challenge-bypass-extension/issues.

---

If you believe that this is a new bug, please proceed to create an issue. The issue will be investigated after you have filled in the following information.

**Describe the bug**
Doesn't do anything on edge

**Expected behavior**
Tokens should be saved and displayed on the extension.

**System (please complete the following information):**
 - OS: Windows 11
 - Cloudflare tokens or hCaptcha tokens? Cloudflare (hCaptcha no longer supports this extension)
 - Browser edge
 - Browser Version latest
 - Privacy Pass Version latest

**Comment by thibmeu** [comment]
Edge is not supported. Support is tracked in #182.

Do you have a link for the extension you have downloaded?

**Comment by cyber-sec0** [comment]
Yes I do

https://chromewebstore.google.com/detail/silk-privacy-pass-client/ajhmfdgkijocedmfjonnpjfojldioehi

**Comment by cyber-sec0** [comment]
@thibmeu 

Yes, I do, I believe that it was the one below, but the name just changed and I saw that it was updated just a few days ago, so maybe it will work now?

https://chromewebstore.google.com/detail/silk-privacy-pass-client/ajhmfdgkijocedmfjonnpjfojldioehi

But now I do not see a page to grab the tokens from, it used to open a test page so I could grab tokens, is that step no longer necessary?
Or what is the website I have to use to grab tokens?

**Comment by thibmeu** [comment]
Extension 4.0.0 does not use non-interactive tokens, and favors interacitive ones.
When a webpage request a Privacy Pass tokens, the extension is going to prompt you to solve a challenge. At the moment, this is limited to a challenge provided by Cloudflare Research, and requiring to solve a Turnstile challenge. More information has been published on [Cloudflare's blog](https://blog.cloudflare.com/privacy-pass-standard).

The extension is still not officially compatible with Edge. It's published on the Chrome Web Store. I've created an issue on Cloudflare repository: https://github.com/cloudflare/pp-browser-extension/issues/9

**Comment by cyber-sec0** [comment]
Ok thank you, so the previous extension used to solve Cloudflare captchas, but now all it does is that users of this extension can expect to see fewer bot-checks around the web?

It sounds a little bit like the extension doesn't do anything anymore because it's hard to know when the extension actually "prevented" me from having to solve a captcha or not...
Is there some sort of indication of when the extension works? Or is it in the plans to add something like this?

**Comment by thibmeu** [comment]
I've added an issue in the extension repository to add an indicator. Should you have suggestions about good indicators, or how you would like the extension to inform you about its work, please comment.

**Comment by cyber-sec0** [comment]
Thank you

Usually, most extensions show a notification by showing a number on the extension icon, or it could be done like Ghostery does, show/add a small icon on the page, or a notification alert fancy box using nice colors and automatically closing it after a few secs.

Perhaps both options could be added and then the user could decide on which one to use, or the user could also use both notification types as well.
