### ISSUE TITLE
Version 4.0.0 not aviable on github

### ISSUE THREAD

**Issue by PeppeMonster** [privacypass/challenge-bypass-extension#408]
i can't see the release of the 4.0.0 version in the repository, i downloaded this version from the chrome web store, 
what is happening? also the name is now is "Silk - Privacy Pass Client" but it was just Privacy Pass

**Comment by aravindvnair99** [comment]
This is the new repo - https://github.com/cloudflare/pp-browser-extension

**Comment by thibmeu** [comment]
Version 4.0.0 has been published by Cloudflare, and is based on [Release 4.0.0](https://github.com/cloudflare/pp-browser-extension/releases/tag/v4.0.0).

A longer explanation is provided in [this blog](https://blog.cloudflare.com/privacy-pass-standard/).
