### ISSUE TITLE
Privacy Pass 3.0.6 on Firefox 121.0 does not grant any passes

### ISSUE THREAD

**Issue by WGrav01** [privacypass/challenge-bypass-extension#409]
Before reporting a new bug, verify if your request is already being tracked by another issue: https://github.com/privacypass/challenge-bypass-extension/issues.

---

If you believe that this is a new bug, please proceed to create an issue. The issue will be investigated after you have filled in the following information.

**Describe the bug**
When filling out a Clouflare or hCaptcha challenge through either the get more passes button or any general captcha, no passes are granted.

**How to reproduce**
1. Install Firefox 121.0, and Privacy Pass 3.0.6
2. Enable "Custom" tracking protection, uncheck all boxes, and disable all website privacy preferences (to avoid potential conflicts)
3. Attempt to obtain passes through Cloudflare, through both the get more passes button and on a general website challenge
4. Attempt to obtain passes through the hCaptcha get more passes button. The captcha on that page is notably missing.
5. [Attempt to obtain passes through this demo.](https://accounts.hcaptcha.com/demo)

**Expected behavior**
Passes should be granted, a captcha should be visible on https://www.hcaptcha.com/privacy-pass.

**System (please complete the following information):**
 - OS:
> Edition:	Windows 11 Home
> Version:	22H2
> Installed on:	‎12/‎15/‎2023
> OS build:	22621.2861
> Experience:	Windows Feature Experience Pack 1000.22681.1000.0

 - Cloudflare tokens or hCaptcha tokens? **Both.**
 - Browser [e.g. chrome, firefox] **Firefox.**
 - Browser Version [e.g. 79, 80, ] **121.0 (20231211174248)**
 - Privacy Pass Version [e.g. 2.0.4, 2.0.5 ] **3.0.6 (as obtained through addons.mozilla.org)**

**Additional context**
Enterprise Policy ImportEnterpriseRoots is set to True, likely through AVG Business Security

**Comment by thibmeu** [comment]
This is expected. Both Cloudflare and hCpatcha stopped providing tokens. See #400
