### ISSUE TITLE
Metadata can theoreticly be used to link tokens with user

### ISSUE THREAD

**Issue by CuteistCat** [privacypass/challenge-bypass-extension#412]
For example u could have a metadata of what the user number is witch basicly removes need for extention as u might as well use something like hcapchas acebilty coockie.

**Comment by thibmeu** [comment]
It can. There is an adoption call happening at IETF right now to discuss the extension of [Privacy Pass to allow metadata](https://datatracker.ietf.org/doc/draft-hendrickson-privacypass-public-metadata/).
hCaptcha accessibility cookie is another tool that can be used to reduce challenge burden on users, but that's not the scope of this extension.

Is there any action you'd like to see this extension take? The ticket title does not seem actionable.

**Comment by CuteistCat** [comment]
i was actuly reading a difrent standard named "tracking pass" (dont ask where i found it) and i mixed it up but i guess theres a extesnion going on

**Comment by CuteistCat** [comment]
for adding metadata to privacy pass
