### ISSUE TITLE
Upload it to Opera Addons

### ISSUE THREAD

**Issue by nipos** [privacypass/challenge-bypass-extension#6]
Could you please upload the extension to Opera Addons?
Since Opera is based on Chromium,its extensions are nearly equal to Chrome extensions.
If you don't use one of the very few different APIs,you only have to change the archive format and upload it.
I'm very happy that Opera and Yandex Browser users have this store and aren't dependent on Googles tracking bullshit.
Please provide some support for it.

Best regards,
an user of Yandex Browser

**Comment by alxdavids** [comment]
I haven't personally looked into extension support for Opera (or Chromium-type browsers in general), but I imagine that this shouldn't be too hard to do.
