### ISSUE TITLE
add a disable or do not send token

### ISSUE THREAD

**Issue by killmetohell** [privacypass/challenge-bypass-extension#61]
Hey when i was redeeming a code on gog some reason the captcha would not let me continue until i disable the privacypass is possible to add a way make so it would not send tokens or make it disable without going to add-ons to disable it. Also if its possible could you find out why did this happen?

**Comment by killmetohell** [comment]
oh good to know but still it would be helpful you can disable/don't send tokens if this kind happens again or otherwise

**Comment by alxdavids** [comment]
It's already possible to clear the tokens that are currently in store, this should be enough without having to disable the extension. We may consider adding a on/off switch further down the line.

**Comment by designeremon** [comment]
Hey my extention doesnt seems to be working , its 0 all the time never gets any pass

**Comment by alxdavids** [comment]
I think don't think we're going to add this. If someone wants to disable the extension, they can do so in the Chrome/FF extension UI.
