### ISSUE TITLE
Confusing "What can I do to prevent this in the future"

### ISSUE THREAD

**Issue by Gitoffthelawn** [privacypass/challenge-bypass-extension#7]
The "What can I do to prevent this in the future" section of the page is confusing.  What is it's purpose?

The current design makes it look like there is an error or malware installed.  I recommend improving the design.

**Comment by alxdavids** [comment]
This is specific to the Cloudflare CAPTCHA page and is not related to Privacy Pass

**Comment by Gitoffthelawn** [comment]
Thanks.  So it's Cloudflare actually showing that information and image?

**Comment by alxdavids** [comment]
Yes, this is a page that Cloudflare shows when a CAPTCHA is triggered. We use https://captcha.website as an example of this behaviour so that it is easier for users to acquire passes, before triggering a CAPTCHA in the wild.

**Comment by alxdavids** [comment]
I'm going to close this.

**Comment by Gitoffthelawn** [comment]
Thanks.  Makes perfect sense now!
