### ISSUE TITLE
double-time spent on hash&increment

### ISSUE THREAD

**Issue by armfazh** [privacypass/challenge-bypass-extension#78]
#### Hash&Increment

On failure, the decoding is taking double of the time since it tries to decode a point with the same `x` coordinate. 

Observe that trying to decode a point using `P = decode( 0x02 || bytes) ` is essentially the same as decoding `P = decode( 0x03 || bytes) `. Both points have the same `x` coordinate but different `y` coordinate. Then, if the first call succeeds, then the point in the second call is just the negative point obtained in the first call.
On the other hand, if the first call fails on decoding a point, the second call will fail as well. Hence it spent twice the time on every failure.

**Comment by alxdavids** [comment]
Thanks for pointing this out, so we just need to remove the second decoding step.

**Comment by armfazh** [comment]
yes, it seems to be the simplest way to fix it

**Comment by alxdavids** [comment]
This has now been fixed.
