### ISSUE TITLE
Possible to maintain bypasses after browser restart?

### ISSUE THREAD

**Issue by Gitoffthelawn** [privacypass/challenge-bypass-extension#8]
Scenario:
1. Start Firefox
2. Generate 30 bypasses (thank you!)
3. Close Firefox
4. Start Firefox again
5. Notice that all bypasses are gone

Is it possible to work on this so the bypasses are maintained across browser sessions?

**Comment by alxdavids** [comment]
I've just tried this and I believe that the passes are persisted. The only thing I did notice is that the icon is greyed out when the browser is first launched. When I click the icon I can see 30 passes. 

Can I just check that this is different to what you are experiencing?

**Comment by jhult** [comment]
FWIW, Chrome seems to persist the passes.

**Comment by Gitoffthelawn** [comment]
@alxdavids That *is* different from what I'm experiencing.  Perhaps it is because the systems here are set to clear the browser's cache when it exits.  Where are the "bypasses" actually stored (for Firefox)?

**Comment by alxdavids** [comment]
The passes are stored in local storage so this may well be the problem.

**Comment by Gitoffthelawn** [comment]
@alxdavids In Firefox, I'm not seeing the passes stored in 'browser-extension-data' or 'storage' folders within the profile.  Where should they be stored?

**Comment by MatzFan** [comment]
This is a known [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1313401) in Firefox. Hopefully it will be resolved such that passes can persist even if a user opts to delete browsing content on exit (as in Chrome).

I would also be interested in the location of the passes in Firefox local storage.

**Comment by Mikaela** [comment]
I am experiencing this with Tor Browser which would probably benefit of this the most. Could this issue and [the Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1313401) be mentioned in the [FAQ](https://privacypass.github.io/faq/) or somewhere similar to decrease confusion as I understand the extension to promise persisting the passes.

I also wonder if there are not that insecure workarounds to this.

**Comment by kingkong8800** [comment]
http://cdn.directapk.net:8085/2018/10/com.fgol.HungrySharkEvolution-224.apk
Észlelési arány: 	4 / 68

**Comment by alxdavids** [comment]
I've added a comment addressing the fact that passes may not be persisted during a restart.

**Comment by Mikaela** [comment]
@alxdavids Could you also mention that it's a browser issue and link there?
