### ISSUE TITLE
Cant' tell if its working or not ...

### ISSUE THREAD

**Issue by ghost** [privacypass/challenge-bypass-extension#96]
Seeing as I'm using a heavily modded user.js and many privacy extensions, I'm not sure PrivacyPass has the right permissions or APIs enabled to properly work ... I get 30 passes when solving captcha.website but still getting 5+ reCAPTCHA loops on other sites.

**Comment by alxdavids** [comment]
Are these reCAPTCHAs that are being shown on Cloudflare-protected websites? Privacy Pass doesn't prevent seeing reCAPTCHAs in general, only those that are hosted on the Cloudflare challenge page.

**Comment by sesam** [comment]
I finally get to to CAPTCHAs on https://captcha.website/ and I did get 30 passes - yay!
But reloading the page, even after trying "Hard reload and remove cache" (a somewhat hidden developer feature in Chrome) I still get the same captcha page, and can't seem to get past it to see the page that used to be there when captchas were not being shown to me. Hm.

**Comment by alxdavids** [comment]
Privacy Pass deliberately avoids spending tokens on captcha.website to prevent token wastage. The extension is currently only intended to improve the browsing experience for users who experience Cloudflare CAPTCHAs (until we support more use-cases).

I'm going to close this issue as the OP hasn't updated with more information. We can reopen if they do.
