### ISSUE TITLE
Tor Browser Bundle not generating tokens

### ISSUE THREAD

**Issue by Thylacine1957** [privacypass/challenge-bypass-extension#99]
As the title says, it seems to have just stopped generating tokens, I have tried it in Firefox 66.0.3 (64-bit) and it works fine there.

Steps to replicate Tor 8.0.8 

Get more Passes
Solve Captcha

Still have the little red box with the 3 exclamation marks showing and zero passes

The only other addons are
Adblock Plus
HTTPS Everywhere
No Coin
No Script
Tab Reloader

I have tried disabling these. but still no joy
As a note the same extensions are installed in Firefox 66.0.3 and as previously stated no issue there.

**Comment by alxdavids** [comment]
Thanks for the information, I will look into this and see if I can replicate.

**Comment by Thylacine1957** [comment]
Just an update still happening in Tor 8.5.1 64 bit

**Comment by Lagicrus** [comment]
Still occurs in Tor 8.5.4 32bit

**Comment by corecontingency** [comment]
Still happens in Tor Browser Bundle 8.5.5 64 bit. Using Arch Linux, and TBB is a completely default config (no extra addons or changed settings) except for installing Privacy Pass addon from [addons.mozilla.org](https://addons.mozilla.org/en-US/firefox/addon/privacy-pass/)

Can the title of this issue be changed to a more general `Tor Browser Bundle not generating tokens`? This is clearly not version specific.

Kinda sucks that this is happening, as it seems like currently this extension doesn't even work with its main use case.

**Comment by alxdavids** [comment]
Thanks for the extra information regarding the UA. You're right, this is something that we should try and fix for the next release and so I will commit some time to looking into it in the next few days.

**Comment by corecontingency** [comment]
@alxdavids 

Thanks!

Trying it several times, it seems to occasionally generate tokens, but very rarely, and I cannot figure what causes it to generate tokens vs. doing nothing.

Seems to act the same whether sandboxed by firejail or not.

Also, seems like even if I have tokens, they get removed the next time I close TBB, although I assume that is a property of Tor browser that you can't do anything about.

**Comment by Thylacine1957** [comment]
When it has worked in the past, there is no issue with it saving the tokens after it is closed, they are still there when it is reopened. I have not been able to get it generate tokens at all since my original report, so you at least have had a bit more success than I

**Comment by sporksmith** [comment]
Still seeing this with Tor Browser Bundle 9.0.5, "standard" security setting, using PrivacyPass 2.0.4, on Ubuntu 18.04.

It seems to work on Firefox routed through Tor (NOT a recommended configuration!), supporting the above hypothesis that it may have to do with user-agent spoofing.

**Comment by Jookia** [comment]
I believe this is due to privacy.resistFingerprinting which is upstream in Firefox now but not disabled by default.

**Comment by alxdavids** [comment]
Yeah I agree, this is related to #106. I'm going to close this issue as a duplicate of the other and will track ongoing investigation there.
